import React, { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { motion } from 'framer-motion';
import { useAuth } from '../src/contexts/AuthContext';
import { useLanguage } from '../src/contexts/LanguageContext';
import { useTheme } from '../src/contexts/ThemeContext';
import ThemeToggle from '../src/components/ui/ThemeToggle';
import LanguageToggle from '../src/components/ui/LanguageToggle';
import Button from '../src/components/ui/Button';
import Logo from '../src/components/ui/Logo';
import { API_BASE_URL } from '../src/lib/config';
import { translations } from '../src/lib/translations';


export default function PartnerRequest() {
  const router = useRouter();
  const { isAuthenticated, loading } = useAuth();
  const { t, isGerman } = useLanguage();
  const { mounted, isDark } = useTheme();
  
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    phone: '',
    email: '',
    pursue: 'moving', // Default to moving service
    company: '',
    address: '',
    city: '',
    zipCode: '',
    country: 'Germany',
    customCountry: '',
    agreeToTerms: false
  }); // Password will be auto-generated by server
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState({});
  const [serverError, setServerError] = useState('');
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const [serviceTypes, setServiceTypes] = useState([]);
  const [loadingServiceTypes, setLoadingServiceTypes] = useState(true);
  const [isServiceDropdownOpen, setIsServiceDropdownOpen] = useState(false);
  const [isPrivacyModalOpen, setIsPrivacyModalOpen] = useState(false);
  const serviceDropdownRef = useRef(null);
  const previousErrorsRef = useRef({});

  useEffect(() => {
    if (isAuthenticated() && !loading) {
      router.push('/dashboard');
    }
  }, [isAuthenticated, loading, router]);

  // Fetch service types from database
  useEffect(() => {
    const fetchServiceTypes = async () => {
      try {
        // Use imported API_BASE_URL from config
        const response = await fetch(`${API_BASE_URL}/services`);
        if (response.ok) {
          const data = await response.json();
          if (data.success && data.services) {
            // Filter to only show moving service
            const movingServices = data.services.filter(service => service.type === 'moving');
            setServiceTypes(movingServices.map(service => ({
              id: service.type,
              name: service.name
            })));
          } else {
            throw new Error('Invalid API response format');
          }
        } else {
          throw new Error(`API returned ${response.status}`);
        }
      } catch (error) {
        console.error('Error fetching service types:', error);
        // Fallback to moving service only
        setServiceTypes([
          { id: 'moving', name: isGerman ? 'Umzugsservice' : 'Moving Service' }
        ]);
      } finally {
        setLoadingServiceTypes(false);
      }
    };

    fetchServiceTypes();
  }, [isGerman]);

  // Update error messages when language changes
  useEffect(() => {
    if (Object.keys(errors).length > 0) {
      // Re-validate to update error messages in current language
      const newErrors = {};

      // First Name validation
      if (!formData.firstName.trim()) {
        newErrors.firstName = isGerman ? 'Vorname ist erforderlich' : 'First name is required';
      }

      // Last Name validation
      if (!formData.lastName.trim()) {
        newErrors.lastName = isGerman ? 'Nachname ist erforderlich' : 'Last name is required';
      }

      // Email validation
      if (!formData.email.trim()) {
        newErrors.email = isGerman ? 'E-Mail ist erforderlich' : 'Email is required';
      } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email.trim())) {
        newErrors.email = isGerman ? 'E-Mail ist ungültig' : 'Email is invalid';
      }

      // Phone validation - removed as per request

      // Service type is always 'moving', no validation needed

      // Company validation
      if (!formData.company.trim()) {
        newErrors.company = isGerman ? 'Firmenname ist erforderlich' : 'Company name is required';
      }

      // Address validation
      if (!formData.address.trim()) {
        newErrors.address = isGerman ? 'Adresse ist erforderlich' : 'Address is required';
      }

      // City validation
      if (!formData.city.trim()) {
        newErrors.city = isGerman ? 'Stadt ist erforderlich' : 'City is required';
      }

      // Zip Code validation
      if (!formData.zipCode.trim()) {
        newErrors.zipCode = isGerman ? 'PLZ ist erforderlich' : 'Zip code is required';
      }

      // Country validation
      if (formData.country === 'Other') {
        if (!formData.customCountry.trim()) {
          newErrors.country = isGerman ? 'Land ist erforderlich' : 'Country is required';
        }
      } else if (!formData.country.trim()) {
        newErrors.country = isGerman ? 'Land ist erforderlich' : 'Country is required';
      }

      // Terms agreement validation
      if (!formData.agreeToTerms) {
        newErrors.agreeToTerms = isGerman ? 'Datenschutzerklärung muss akzeptiert werden' : 'Privacy policy must be accepted';
      }

      // Update errors only if there were existing errors for those fields
      const updatedErrors = {};
      Object.keys(errors).forEach(key => {
        if (newErrors[key]) {
          updatedErrors[key] = newErrors[key];
        }
      });

      if (Object.keys(updatedErrors).length > 0) {
        setErrors(updatedErrors);
      }
    }
  }, [isGerman, formData.firstName, formData.lastName, formData.email, formData.phone, formData.pursue, formData.company, formData.address, formData.city, formData.zipCode, formData.country, formData.customCountry, formData.agreeToTerms, errors]);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (serviceDropdownRef.current && !serviceDropdownRef.current.contains(event.target)) {
        setIsServiceDropdownOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;

    // Special handling for country dropdown
    if (name === 'country' && value === 'Other') {
      setFormData(prev => ({
        ...prev,
        country: 'Other',
        customCountry: '' // Reset custom country when "Other" is selected
      }));
      return;
    }

    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
    
    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  // Translate server error messages using translations file
  const getTranslatedError = (errorMsg) => {
    const lang = isGerman ? 'de' : 'en';
    const trans = translations[lang];

    // Try to find the error message in translations
    return trans.auth[errorMsg] || errorMsg;
  };

  const validateForm = () => {
    const newErrors = {};

    // First Name validation
    if (!formData.firstName.trim()) {
      newErrors.firstName = isGerman ? 'Vorname ist erforderlich' : 'First name is required';
    }

    // Last Name validation
    if (!formData.lastName.trim()) {
      newErrors.lastName = isGerman ? 'Nachname ist erforderlich' : 'Last name is required';
    }

    // Email validation
    if (!formData.email.trim()) {
      newErrors.email = isGerman ? 'E-Mail ist erforderlich' : 'Email is required';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email.trim())) {
      newErrors.email = isGerman ? 'E-Mail ist ungültig' : 'Email is invalid';
    }

    // Phone validation - removed as per request

    // Service type is always 'moving', no validation needed

    // Company validation
    if (!formData.company.trim()) {
      newErrors.company = isGerman ? 'Firmenname ist erforderlich' : 'Company name is required';
    }

    // Address validation
    if (!formData.address.trim()) {
      newErrors.address = isGerman ? 'Adresse ist erforderlich' : 'Address is required';
    }

    // City validation
    if (!formData.city.trim()) {
      newErrors.city = isGerman ? 'Stadt ist erforderlich' : 'City is required';
    }

    // Zip Code validation
    if (!formData.zipCode.trim()) {
      newErrors.zipCode = isGerman ? 'PLZ ist erforderlich' : 'Zip code is required';
    }

    // Country validation
    if (formData.country === 'Other') {
      if (!formData.customCountry.trim()) {
        newErrors.country = isGerman ? 'Land ist erforderlich' : 'Country is required';
      }
    } else if (!formData.country.trim()) {
      newErrors.country = isGerman ? 'Land ist erforderlich' : 'Country is required';
    }

    // Terms agreement validation
    if (!formData.agreeToTerms) {
      newErrors.agreeToTerms = isGerman ? 'Datenschutzerklärung muss akzeptiert werden' : 'Privacy policy must be accepted';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Get the first error for top display and auto-focus
  const getFirstError = () => {
    const errorKeys = [
      'firstName', 'lastName', 'email', 'phone', 'pursue', 'company', 'address', 'city', 'zipCode', 'country', 'agreeToTerms'
    ];
    
    for (const key of errorKeys) {
      if (errors[key]) {
        return { field: key, message: errors[key] };
      }
    }
    
    return null;
  };

  // Auto-focus on problematic field
  const focusOnErrorField = () => {
    const firstError = getFirstError();
    if (firstError) {
      setTimeout(() => {
        const element = document.getElementById(firstError.field);
        if (element) {
          element.focus();
          element.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
      }, 100);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!validateForm()) {
      focusOnErrorField();
      return;
    }

    setIsSubmitting(true);
    
    try {
      // Send partner registration request to backend
      // Use imported API_BASE_URL from config
      const response = await fetch(`${API_BASE_URL}/auth/register-partner`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          companyName: formData.company,
          contactPerson: {
            firstName: formData.firstName,
            lastName: formData.lastName,
            email: formData.email,
            phone: formData.phone
          },
          address: {
            street: formData.address,
            city: formData.city,
            zipCode: formData.zipCode,
            country: formData.country === 'Other' ? formData.customCountry : formData.country
          },
          // Password will be auto-generated by server
          services: ['moving'], // Only moving service supported
          partnerType: 'basic',
          language: isGerman ? 'de' : 'en' // Add current language preference
        }),
      });

      const result = await response.json();

      if (response.ok && result.success) {
        setSubmitSuccess(true);
        console.log('Registration successful:', result);

        // Clear any existing errors
        setErrors({});
        setServerError('');

        // Do not auto-redirect - let user click the button
      } else {
        // Handle validation errors
        if (result.errors && Array.isArray(result.errors)) {
          const newErrors = {};
          result.errors.forEach(error => {
            const field = error.path || error.param;
            const translatedMsg = getTranslatedError(error.msg);
            // Map backend nested fields to frontend flat fields
            if (field === 'contactPerson.firstName') newErrors.firstName = translatedMsg;
            else if (field === 'contactPerson.lastName') newErrors.lastName = translatedMsg;
            else if (field === 'contactPerson.email') newErrors.email = translatedMsg;
            else if (field === 'contactPerson.phone') newErrors.phone = translatedMsg;
            else if (field === 'companyName') newErrors.company = translatedMsg;
            else if (field === 'address.street') newErrors.address = translatedMsg;
            else if (field === 'address.city') newErrors.city = translatedMsg;
            else if (field === 'address.zipCode' || field === 'address.postalCode') newErrors.zipCode = translatedMsg;
            else if (field === 'address.country') newErrors.country = translatedMsg;
            else if (field === 'services') newErrors.pursue = translatedMsg;
            else newErrors.email = translatedMsg; // Default to email field
          });
          setErrors(newErrors);
          setServerError('');
        } else {
          // Handle specific error messages - show as server error
          setErrors({});
          if (result.message?.includes('email already exists')) {
            setServerError(
              isGerman
                ? 'Ein Partner mit dieser E-Mail-Adresse existiert bereits.'
                : 'A partner with this email address already exists.'
            );
          } else if (result.message?.includes('Services already registered')) {
            setServerError(
              isGerman
                ? 'Services bereits registriert: ' + (result.message?.includes('moving') ? 'Umzug' : result.message?.includes('cleaning') ? 'Reinigung' : 'Service') + '. Duplizierte Services können nicht registriert werden, es sei denn, sie wurden zuvor abgelehnt.'
                : result.message
            );
          } else if (result.message?.includes('company name already exists') || result.message?.includes('Company') && result.message?.includes('already offers')) {
            setServerError(
              isGerman
                ? 'Ein Partner mit diesem Firmennamen bietet bereits diesen Service an.'
                : 'A partner with this company name already offers this service.'
            );
          } else {
            setServerError(
              result.message || (isGerman
                ? 'Partner-Registrierung fehlgeschlagen'
                : 'Partner registration failed')
            );
          }
        }
      }
      
    } catch (error) {
      console.error('Registration error:', error);
      setErrors({ 
        email: isGerman 
          ? 'Netzwerkfehler. Bitte versuchen Sie es erneut.' 
          : 'Network error. Please try again.' 
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!mounted) {
    return null;
  }

  if (loading) {
    return (
      <div 
        className="min-h-screen flex items-center justify-center"
        style={{ 
          backgroundColor: 'var(--theme-bg)',
          backgroundImage: 'radial-gradient(circle at 25% 25%, rgba(99, 102, 241, 0.1) 0%, transparent 50%), radial-gradient(circle at 75% 75%, rgba(236, 72, 153, 0.1) 0%, transparent 50%)'
        }}
      >
        <motion.div
          className="flex flex-col items-center space-y-4"
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
        >
          <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
          <p style={{ color: 'var(--theme-text)' }}>
            {isGerman ? 'Wird geladen...' : 'Loading...'}
          </p>
        </motion.div>
      </div>
    );
  }

  if (isAuthenticated()) {
    return null;
  }

  if (submitSuccess) {
    return (
      <div 
        className="min-h-screen flex items-center justify-center relative overflow-hidden"
        style={{ 
          backgroundColor: 'var(--theme-bg)', 
          color: 'var(--theme-text)',
          backgroundImage: 'radial-gradient(circle at 25% 25%, rgba(99, 102, 241, 0.1) 0%, transparent 50%), radial-gradient(circle at 75% 75%, rgba(236, 72, 153, 0.1) 0%, transparent 50%)'
        }}
      >
        <motion.div
          className="text-center p-8 max-w-md mx-4"
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6 }}
        >
          <motion.div
            className="text-6xl mb-6"
            animate={{ rotate: [0, 10, -10, 0], scale: [1, 1.1, 1] }}
            transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
          >
            ✅
          </motion.div>
          <h2 className="text-3xl font-bold mb-4">
            {isGerman ? 'Anfrage gesendet!' : 'Request Sent!'}
          </h2>
          <p className="text-lg mb-4" style={{ color: 'var(--theme-muted)' }}>
            {isGerman
              ? 'Vielen Dank für Ihr Interesse! Wir werden uns bald bei Ihnen melden.'
              : 'Thank you for your interest! We will contact you soon.'
            }
          </p>

          <motion.div
            className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 rounded-lg p-4 mb-6"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
          >
            <div className="flex items-start space-x-3">
              <svg className="w-5 h-5 text-blue-600 dark:text-blue-400 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              <p className="text-sm text-blue-800 dark:text-blue-200">
                {isGerman
                  ? 'Eine Bestätigungs-E-Mail wurde an Ihre E-Mail-Adresse gesendet. Bitte überprüfen Sie Ihr Postfach.'
                  : 'A confirmation email has been sent to your email address. Please check your inbox.'
                }
              </p>
            </div>
          </motion.div>

          <motion.button
            onClick={() => router.push('/partner-login')}
            className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-semibold py-3 px-6 rounded-lg shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center space-x-2"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.6 }}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
          >
            <span>{isGerman ? 'Zur Anmeldung' : 'Go to Login'}</span>
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </motion.button>
        </motion.div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>
          {isGerman ? 'Registrieren - Umzug Anbieter Vergleich' : 'Register - Umzug Anbieter Vergleich'}
        </title>
        <meta name="description" content={isGerman ? 'Erstellen Sie Ihr kostenloses Umzug Anbieter Vergleich Konto' : 'Create your free Umzug Anbieter Vergleich account'} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes" />
      </Head>

      <div 
        className="min-h-screen flex flex-col lg:flex-row relative"
        style={{ 
          backgroundColor: 'var(--theme-bg)', 
          color: 'var(--theme-text)',
          backgroundImage: 'radial-gradient(circle at 25% 25%, rgba(99, 102, 241, 0.1) 0%, transparent 50%), radial-gradient(circle at 75% 75%, rgba(236, 72, 153, 0.1) 0%, transparent 50%)'
        }}
      >
        {/* Animated Background Elements */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <motion.div
            className="absolute top-20 left-20 w-32 h-32 bg-gradient-to-r from-blue-400 to-purple-500 rounded-full opacity-20 blur-3xl"
            animate={{
              x: [0, 50, 0],
              y: [0, -30, 0],
              scale: [1, 1.2, 1],
            }}
            transition={{
              duration: 8,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
          <motion.div
            className="absolute bottom-20 right-20 w-48 h-48 bg-gradient-to-r from-pink-400 to-red-500 rounded-full opacity-20 blur-3xl"
            animate={{
              x: [0, -40, 0],
              y: [0, 20, 0],
              scale: [1, 0.8, 1],
            }}
            transition={{
              duration: 10,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
        </div>

        {/* Main Form Container */}
        <div className="flex-1 flex flex-col py-4 sm:py-6 px-4 sm:px-6 lg:px-8 relative z-10 overflow-y-auto">
          <div className="mx-auto w-full max-w-sm sm:max-w-md lg:max-w-2xl my-auto">
            {/* Header Controls */}
            <motion.div
              className="flex items-center justify-between mb-2 sm:mb-3"
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <Logo />
              <div className="flex items-center space-x-2 sm:space-x-3">
                <LanguageToggle />
                <ThemeToggle />
              </div>
            </motion.div>

            {/* Partner Request Card */}
            <motion.div
              className="backdrop-blur-xl rounded-xl p-4 sm:p-6 border shadow-2xl relative"
              style={{
                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                borderColor: 'var(--theme-border)',
                boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)'
              }}
              initial={{ opacity: 0, y: 30, scale: 0.9 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              transition={{ duration: 0.8, delay: 0.2 }}
            >
              {/* Glass Effect Overlay */}
              <div className="absolute inset-0 bg-gradient-to-br from-white/10 to-white/5 rounded-2xl pointer-events-none" />
              
              <div className="relative z-10">
                {/* Back Button */}
                <motion.div
                  className="mb-4"
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.5 }}
                >
                  <Link
                    href="/partner-login"
                    className="inline-flex items-center text-sm font-medium transition-all duration-200 hover:opacity-75"
                    style={{ color: 'var(--theme-accent)' }}
                  >
                    <motion.span
                      animate={{ x: [-2, 0, -2] }}
                      transition={{ duration: 1.5, repeat: Infinity, ease: "easeInOut" }}
                      className="mr-2"
                    >
                      ←
                    </motion.span>
                    {isGerman ? 'Zurück zur Anmeldung' : 'Back to Login'}
                  </Link>
                </motion.div>

                <div className="text-center mb-4 sm:mb-5">
                  <motion.div
                    className="w-12 h-12 sm:w-14 sm:h-14 mx-auto mb-2 bg-gradient-to-br from-green-500 via-blue-500 to-purple-500 rounded-xl flex items-center justify-center shadow-lg"
                    initial={{ scale: 0, rotate: -180 }}
                    animate={{ scale: 1, rotate: 0 }}
                    transition={{ 
                      type: "spring", 
                      stiffness: 200, 
                      damping: 15,
                      delay: 0.4 
                    }}
                    whileHover={{ 
                      scale: 1.1, 
                      rotate: 10,
                      boxShadow: "0 10px 25px rgba(34, 197, 94, 0.4)"
                    }}
                  >
                    <span className="text-xl sm:text-2xl text-white">🤝</span>
                  </motion.div>
                  <motion.h2 
                    className="text-xl sm:text-3xl font-bold mb-2 sm:mb-3 bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.5 }}
                  >
                    {isGerman ? 'Registrieren' : 'Create Account'}
                  </motion.h2>
                  <motion.p 
                    className="text-base sm" 
                    style={{ color: 'var(--theme-muted)' }}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.6 }}
                  >
                    {isGerman 
                      ? 'Erstellen Sie Ihr Umzug Anbieter Vergleich Konto'
                      : 'Create your Umzug Anbieter Vergleich Partner account'
                    }
                  </motion.p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-4 sm:space-y-6">
                  {/* Server Error Message */}
                  {serverError && (
                    <motion.div
                      initial={{ opacity: 0, scale: 0.9 }}
                      animate={{ opacity: 1, scale: 1 }}
                      className="p-4 rounded-xl border border-red-400/30 bg-red-50 text-red-700 text-sm text-center"
                      style={{
                        backgroundColor: 'rgba(239, 68, 68, 0.1)',
                        borderColor: 'rgba(239, 68, 68, 0.3)',
                        color: '#991b1b'
                      }}
                    >
                      ⚠️ {serverError}
                    </motion.div>
                  )}

                  {/* Name Fields - Two Columns */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {/* First Name */}
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.7 }}
                    >
                      <label 
                        htmlFor="firstName" 
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        👤 {isGerman ? 'Vorname' : 'First Name'}
                      </label>
                      <div className="relative">
                        <input
                          id="firstName"
                          name="firstName"
                          type="text"
                          required
                          value={formData.firstName}
                          onChange={handleChange}
                          onInvalid={(e) => {
                            e.target.setCustomValidity(
                              isGerman 
                                ? 'Bitte füllen Sie dieses Feld aus.' 
                                : 'Please fill in this field.'
                            );
                          }}
                          onInput={(e) => e.target.setCustomValidity('')}
                          className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                          style={{
                            backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                            color: 'var(--theme-text)',
                            backdropFilter: 'blur(10px)'
                          }}
                          placeholder={isGerman ? 'Vorname eingeben' : 'Enter first name'}
                        />
                      </div>
                    </motion.div>

                    {/* Last Name */}
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.8 }}
                    >
                      <label 
                        htmlFor="lastName" 
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        👤 {isGerman ? 'Nachname' : 'Last Name'}
                      </label>
                      <div className="relative">
                        <input
                          id="lastName"
                          name="lastName"
                          type="text"
                          required
                          value={formData.lastName}
                          onChange={handleChange}
                          onInvalid={(e) => {
                            e.target.setCustomValidity(
                              isGerman 
                                ? 'Bitte füllen Sie dieses Feld aus.' 
                                : 'Please fill in this field.'
                            );
                          }}
                          onInput={(e) => e.target.setCustomValidity('')}
                          className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                          style={{
                            backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                            color: 'var(--theme-text)',
                            backdropFilter: 'blur(10px)'
                          }}
                          placeholder={isGerman ? 'Nachname eingeben' : 'Enter last name'}
                        />
                      </div>
                    </motion.div>
                  </div>

                  {/* Email and Phone - Two Columns */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {/* Email */}
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.9 }}
                    >
                      <label 
                        htmlFor="email" 
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        📧 E-Mail
                      </label>
                      <div className="relative">
                        <input
                          id="email"
                          name="email"
                          type="email"
                          required
                          value={formData.email}
                          onChange={handleChange}
                          onInvalid={(e) => {
                            e.target.setCustomValidity(
                              isGerman 
                                ? 'Bitte füllen Sie dieses Feld aus.' 
                                : 'Please fill in this field.'
                            );
                          }}
                          onInput={(e) => e.target.setCustomValidity('')}
                          className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                          style={{
                            backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                            color: 'var(--theme-text)',
                            backdropFilter: 'blur(10px)'
                          }}
                          placeholder={isGerman ? 'E-Mail-Adresse eingeben' : 'Enter email address'}
                        />
                      </div>
                    </motion.div>

                    {/* Phone */}
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 1.0 }}
                    >
                      <label 
                        htmlFor="phone" 
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        📞 {isGerman ? 'Telefonnummer' : 'Phone Number'}
                      </label>
                      <div className="relative">
                        <input
                          id="phone"
                          name="phone"
                          type="tel"
                          required
                          value={formData.phone}
                          onChange={handleChange}
                          onInvalid={(e) => {
                            e.target.setCustomValidity(
                              isGerman
                                ? 'Bitte füllen Sie dieses Feld aus.'
                                : 'Please fill in this field.'
                            );
                          }}
                          onInput={(e) => e.target.setCustomValidity('')}
                          className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                          style={{
                            backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                            color: 'var(--theme-text)',
                            backdropFilter: 'blur(10px)'
                          }}
                          placeholder={isGerman ? 'Telefonnummer eingeben' : 'Enter phone number'}
                        />
                      </div>
                    </motion.div>
                  </div>

                  {/* Service is fixed to moving - no selection needed */}

                  {/* Company Name - Half Width */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 1.2 }}
                    >
                      <label 
                        htmlFor="company" 
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        🏢 {isGerman ? 'Firmenname' : 'Company Name'}
                      </label>
                      <div className="relative">
                        <input
                          id="company"
                          name="company"
                          type="text"
                          required
                          value={formData.company}
                          onChange={handleChange}
                          onInvalid={(e) => {
                            e.target.setCustomValidity(
                              isGerman 
                                ? 'Bitte füllen Sie dieses Feld aus.' 
                                : 'Please fill in this field.'
                            );
                          }}
                          onInput={(e) => e.target.setCustomValidity('')}
                          className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                          style={{
                            backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                            color: 'var(--theme-text)',
                            backdropFilter: 'blur(10px)'
                          }}
                          placeholder={isGerman ? 'Firmenname eingeben' : 'Enter company name'}
                        />
                      </div>
                    </motion.div>

                    {/* Zip Code */}
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 1.25 }}
                    >
                      <label
                        htmlFor="zipCode"
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        📮 {isGerman ? 'PLZ' : 'Zip Code'}
                      </label>
                      <div className="relative">
                        <input
                          id="zipCode"
                          name="zipCode"
                          type="text"
                          required
                          value={formData.zipCode}
                          onChange={handleChange}
                          onInvalid={(e) => {
                            e.target.setCustomValidity(
                              isGerman
                                ? 'Bitte füllen Sie dieses Feld aus.'
                                : 'Please fill in this field.'
                            );
                          }}
                          onInput={(e) => e.target.setCustomValidity('')}
                          className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                          style={{
                            backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                            color: 'var(--theme-text)',
                            backdropFilter: 'blur(10px)'
                          }}
                          placeholder={isGerman ? '10115' : '10115'}
                        />
                      </div>
                    </motion.div>
                  </div>

                  {/* Street Address - Full Width */}
                  <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 1.3 }}
                  >
                    <label
                      htmlFor="address"
                      className="block text-sm font-semibold mb-3"
                      style={{ color: 'var(--theme-text)' }}
                    >
                      📍 {isGerman ? 'Straße und Hausnummer' : 'Street and House Number'}
                    </label>
                    <div className="relative">
                      <input
                        id="address"
                        name="address"
                        type="text"
                        required
                        value={formData.address}
                        onChange={handleChange}
                        onInvalid={(e) => {
                          e.target.setCustomValidity(
                            isGerman
                              ? 'Bitte füllen Sie dieses Feld aus.'
                              : 'Please fill in this field.'
                          );
                        }}
                        onInput={(e) => e.target.setCustomValidity('')}
                        className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                        style={{
                          backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                          color: 'var(--theme-text)',
                          backdropFilter: 'blur(10px)'
                        }}
                        placeholder={isGerman ? 'Musterstraße 123' : 'Musterstraße 123'}
                      />
                    </div>
                  </motion.div>

                  {/* City and Country */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {/* City */}
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 1.5 }}
                    >
                      <label
                        htmlFor="city"
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        🏙️ {isGerman ? 'Stadt' : 'City'}
                      </label>
                      <div className="relative">
                        <input
                          id="city"
                          name="city"
                          type="text"
                          required
                          value={formData.city}
                          onChange={handleChange}
                          onInvalid={(e) => {
                            e.target.setCustomValidity(
                              isGerman
                                ? 'Bitte füllen Sie dieses Feld aus.'
                                : 'Please fill in this field.'
                            );
                          }}
                          onInput={(e) => e.target.setCustomValidity('')}
                          className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                          style={{
                            backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                            color: 'var(--theme-text)',
                            backdropFilter: 'blur(10px)'
                          }}
                          placeholder={isGerman ? 'Berlin' : 'Berlin'}
                        />
                      </div>
                    </motion.div>

                    {/* Country */}
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 1.6 }}
                    >
                      <label
                        htmlFor="country"
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        🌍 {isGerman ? 'Land' : 'Country'}
                      </label>
                      <div className="relative">
                        {formData.country === 'Other' ? (
                          <input
                            id="customCountry"
                            name="customCountry"
                            type="text"
                            required
                            value={formData.customCountry}
                            onChange={(e) => {
                              setFormData(prev => ({
                                ...prev,
                                customCountry: e.target.value
                              }));
                            }}
                            onInvalid={(e) => {
                              e.target.setCustomValidity(
                                isGerman
                                  ? 'Bitte füllen Sie dieses Feld aus.'
                                  : 'Please fill in this field.'
                              );
                            }}
                            onInput={(e) => e.target.setCustomValidity('')}
                            className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                            style={{
                              backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                              color: 'var(--theme-text)',
                              backdropFilter: 'blur(10px)'
                            }}
                            placeholder={isGerman ? 'Land eingeben...' : 'Enter country...'}
                          />
                        ) : (
                          <select
                            id="country"
                            name="country"
                            required
                            value={formData.country}
                            onChange={handleChange}
                            onInvalid={(e) => {
                              e.target.setCustomValidity(
                                isGerman
                                  ? 'Bitte füllen Sie dieses Feld aus.'
                                  : 'Please fill in this field.'
                              );
                            }}
                            onInput={(e) => e.target.setCustomValidity('')}
                            className="appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 border-gray-300 dark:border-gray-200/30 rounded-xl backdrop-blur-sm transition-all duration-300 focus:outline-none focus:ring-4 focus:ring-blue-400 focus:ring-opacity-30 focus:border-blue-400 focus:scale-105 text-sm sm:text-base"
                            style={{
                              backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05))',
                              color: 'var(--theme-text)',
                              backdropFilter: 'blur(10px)'
                            }}
                          >
                            <option value="Germany">🇩🇪 Deutschland</option>
                            <option value="Austria">🇦🇹 Österreich</option>
                            <option value="Switzerland">🇨🇭 Schweiz</option>
                            <option value="Netherlands">🇳🇱 Nederland</option>
                            <option value="France">🇫🇷 France</option>
                            <option value="Italy">🇮🇹 Italia</option>
                            <option value="Spain">🇪🇸 España</option>
                            <option value="Other">{isGerman ? 'Andere' : 'Other'}</option>
                          </select>
                        )}
                      </div>
                    </motion.div>
                  </div>

                  {/* Privacy Policy Checkbox - Password will be auto-generated by server */}
                  <motion.div 
                    className="flex items-center justify-center mb-4 sm:mb-6"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 1.5 }}
                  >
                    <div className="flex items-start space-x-3">
                      <input
                        id="agreeToTerms"
                        name="agreeToTerms"
                        type="checkbox"
                        required
                        checked={formData.agreeToTerms}
                        onChange={handleChange}
                        onInvalid={(e) => {
                          e.target.setCustomValidity(
                            isGerman 
                              ? 'Bitte kreuzen Sie dieses Kästchen an, wenn Sie fortfahren möchten.' 
                              : 'Please tick this box if you want to proceed.'
                          );
                        }}
                        onInput={(e) => e.target.setCustomValidity('')}
                        className={`mt-1 h-4 w-4 rounded focus:ring-blue-500 ${
                          errors.agreeToTerms 
                            ? 'border-red-400 text-red-600' 
                            : 'border-gray-300 text-blue-600'
                        }`}
                      />
                      <div className="flex-1">
                        <label htmlFor="agreeToTerms" className="text-sm font-medium" style={{ color: 'var(--theme-text)' }}>
                          {isGerman
                            ? <>
                                <button
                                  type="button"
                                  onClick={() => setIsPrivacyModalOpen(true)}
                                  className="text-blue-600 hover:text-blue-700 underline font-semibold transition-colors duration-200"
                                >
                                  Datenschutzerklärung
                                </button>
                                {' und AGB akzeptieren *'}
                              </>
                            : <>
                                {'Accept '}
                                <button
                                  type="button"
                                  onClick={() => setIsPrivacyModalOpen(true)}
                                  className="text-blue-600 hover:text-blue-700 underline font-semibold transition-colors duration-200"
                                >
                                  privacy policy
                                </button>
                                {' and terms *'}
                              </>
                          }
                        </label>
                      </div>
                    </div>
                  </motion.div>

                  {/* Submit Button */}
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 1.6 }}
                  >
                    <Button
                      type="submit"
                      disabled={isSubmitting}
                      loading={isSubmitting}
                      variant="primary"
                      size="lg"
                      fullWidth
                      className="group relative text-sm sm:text-base font-bold text-white focus:ring-4 focus:ring-blue-500/30 bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 hover:from-blue-700 hover:via-purple-700 hover:to-pink-700"
                    >
                      {!isSubmitting && (
                        <>
                          <motion.span
                            animate={{ rotate: [0, 10, -10, 0] }}
                            transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
                            className="mr-2 text-lg"
                          >
                            🚀
                          </motion.span>
                          <span>{isGerman ? 'Als Partner registrieren' : 'Register as Partner'}</span>
                          <motion.span
                            animate={{ x: [0, 5, 0] }}
                            transition={{ duration: 1.5, repeat: Infinity, ease: "easeInOut" }}
                            className="ml-2"
                          >
                            →
                          </motion.span>
                        </>
                      )}
                      {isSubmitting && (
                        <span>{isGerman ? 'Partner-Registrierung läuft...' : 'Registering partner...'}</span>
                      )}
                    </Button>
                  </motion.div>

                  {/* Back to Login Link */}
                  <motion.div 
                    className="text-center mt-6 pt-4 sm:mt-8 sm:pt-6 border-t border-gray-200/20"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 1.6 }}
                  >
                    <span className="text-sm" style={{ color: 'var(--theme-muted)' }}>
                      {isGerman ? 'Bereits registriert?' : 'Already registered?'}{' '}
                      <Link
                        href="/partner-login"
                        className="font-semibold transition-all duration-200 hover:underline bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent"
                      >
                        {isGerman ? 'Anmelden' : 'Sign In'}
                      </Link>
                    </span>
                  </motion.div>
                </form>

                {/* Privacy Policy Modal */}
                {isPrivacyModalOpen && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
                    onClick={() => setIsPrivacyModalOpen(false)}
                  >
                    <motion.div
                      initial={{ opacity: 0, scale: 0.95, y: 20 }}
                      animate={{ opacity: 1, scale: 1, y: 0 }}
                      exit={{ opacity: 0, scale: 0.95, y: 20 }}
                      onClick={(e) => e.stopPropagation()}
                      className="bg-white dark:bg-gray-900 rounded-2xl shadow-2xl max-w-2xl w-full max-h-[80vh] overflow-y-auto"
                    >
                      <div className="sticky top-0 bg-gradient-to-r from-blue-600 to-purple-600 p-6 flex justify-between items-center z-10">
                        <h2 className="text-2xl font-bold text-white">
                          {isGerman ? 'Datenschutz' : 'Data Protection'}
                        </h2>
                        <button
                          onClick={() => setIsPrivacyModalOpen(false)}
                          className="text-white hover:bg-white/20 rounded-lg p-2 transition-colors duration-200"
                        >
                          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      </div>

                      <div className="p-6 space-y-4 text-sm leading-relaxed" style={{ color: 'var(--theme-text)' }}>
                        {isGerman ? (
                          <>
                            <h3 className="text-lg font-bold mb-4">Datenschutz- und Sicherheitsrichtlinie</h3>
                            <p>Der Schutz Ihrer Privatsphäre ist uns wichtig, und wir verpflichten uns, Ihre personenbezogenen Daten gemäß strengen Standards zu schützen.</p>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">1. Sicherheit</h4>
                              <p>Die Sicherheit Ihrer personenbezogenen Daten hat für uns höchste Priorität. Wir verwenden Secure Sockets Layer (SSL)-Technologie, um Ihre Daten zu schützen. Wenn Ihr Browser SSL unterstützt, werden die Informationen, die Sie auf sicheren Seiten eingeben, automatisch verschlüsselt, bevor sie über das Internet gesendet werden.</p>
                              <p className="mt-2">Ein geschlossenes Vorhängeschloss oder ein ungebrochenes Schlüsselsymbol in Ihrem Browser zeigt an, dass Sie mit unserem sicheren Server verbunden sind und Ihre Daten geschützt sind.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">2. Cookies</h4>
                              <p>Wir verwenden Cookies, kleine Textdateien, die von Ihrem Browser auf Ihrem Computer gespeichert werden, um zu analysieren, wie Kunden mit unserer Website interagieren.</p>
                              <p className="mt-2">Diese Cookies helfen uns, unsere Website zu verbessern und an Ihre Präferenzen anzupassen. Die gesammelten Daten werden ausschließlich zur Optimierung Ihrer Benutzererfahrung verwendet und nicht an Dritte weitergegeben.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">3. Registrierung</h4>
                              <p>Wir empfehlen Ihnen, sich auf unserer Website zu registrieren und anzumelden, um personalisierte Funktionen wie Bestellstatus und individuelle Informationen zu Ihrem Konto zu nutzen.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">4. Bestellungen aufgeben</h4>
                              <p>Wenn Sie eine Bestellung aufgeben, erheben wir die erforderlichen Informationen, darunter:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li>Ihren Namen</li>
                                <li>Ihre Rechnungs- und Lieferadresse</li>
                                <li>Ihre Zahlungsinformationen</li>
                                <li>Ihre Kontaktdaten</li>
                              </ul>
                              <p className="mt-2">Diese Daten helfen uns, Ihre Bestellung reibungslos abzuwickeln und Ihnen ein angenehmes Einkaufserlebnis zu bieten. Ihre Daten werden ausschließlich für die Abwicklung Ihrer Transaktion verwendet.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">5. Weitergabe von Informationen</h4>
                              <p>Um Ihnen unsere Dienstleistungen bereitzustellen, einschließlich Verifizierung, Betrugsprävention, Zahlungsabwicklung und Versand, können wir Ihre Daten mit vertrauenswürdigen Geschäftspartnern teilen.</p>
                              <p className="mt-2">In bestimmten Fällen, z.B. zur Betrugserkennung, können personenbezogene Daten an Behörden oder andere Organisationen weitergegeben werden, die diese Informationen speichern und später darauf zugreifen können.</p>
                              <p className="mt-2">Wir können Daten auch weitergeben, wenn dies gesetzlich vorgeschrieben ist oder zum Schutz unserer Rechte und unseres Eigentums erforderlich ist.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">6. Datenspeicherung</h4>
                              <p>Wir bewahren Ihre personenbezogenen Daten nur so lange auf, wie es für die Zwecke erforderlich ist, für die sie erhoben wurden. Dies umfasst gesetzliche, buchhalterische oder Berichtspflichten.</p>
                              <p className="mt-2">Sobald Ihre Daten nicht mehr benötigt werden, ergreifen wir geeignete Maßnahmen, um sie sicher zu löschen oder zu anonymisieren.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">7. Ihre Datenschutzrechte</h4>
                              <p>Abhängig von Ihrem Standort haben Sie möglicherweise folgende Rechte:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li>Auskunft über Ihre personenbezogenen Daten zu verlangen</li>
                                <li>Die Berichtigung oder Löschung Ihrer Daten zu verlangen</li>
                                <li>Der Verarbeitung Ihrer Daten in bestimmten Fällen zu widersprechen</li>
                              </ul>
                              <p className="mt-2">Um diese Rechte auszuüben, kontaktieren Sie uns bitte über die unten angegebenen Kontaktdaten.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">8. Abmeldung von Marketing-Mitteilungen</h4>
                              <p>Wenn Sie keine Marketing-E-Mails mehr von uns erhalten möchten, können Sie sich jederzeit abmelden:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li>Nutzen Sie den Abmeldelink am Ende unserer E-Mails.</li>
                                <li>Kontaktieren Sie uns direkt</li>
                              </ul>
                              <p className="mt-2">Bitte beachten Sie, dass Sie auch nach der Abmeldung von Werbe-E-Mails weiterhin wichtige transaktionsbezogene oder administrative Nachrichten zu Ihren Bestellungen oder Ihrem Konto erhalten können.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">9. Datenschutz für Kinder</h4>
                              <p>Unsere Website und Dienstleistungen sind nicht für Kinder unter 13 Jahren bestimmt.</p>
                              <p className="mt-2">Wir erheben oder speichern wissentlich keine personenbezogenen Daten von Kindern unter 13 Jahren. Wenn wir feststellen, dass ein Kind unter 13 Jahren uns personenbezogene Daten übermittelt hat, werden wir diese umgehend löschen.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">10. Änderungen dieser Datenschutzrichtlinie</h4>
                              <p>Wir behalten uns das Recht vor, diese Datenschutzrichtlinie von Zeit zu Zeit zu aktualisieren.</p>
                              <p className="mt-2">Alle Änderungen werden auf dieser Seite veröffentlicht, und das Datum der letzten Aktualisierung wird oben in der Richtlinie angepasst.</p>
                              <p className="mt-2">Wir empfehlen Ihnen, diese Richtlinie regelmäßig zu überprüfen, um informiert zu bleiben, wie wir Ihre personenbezogenen Daten schützen.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">11. Internationale Datenübertragungen</h4>
                              <p>Wenn Sie sich außerhalb der Region befinden, in der unsere Website betrieben wird, beachten Sie bitte, dass Ihre personenbezogenen Daten in ein anderes Land übertragen und dort verarbeitet werden können.</p>
                              <p className="mt-2">Durch die Nutzung unserer Website und die Bereitstellung Ihrer Informationen stimmen Sie solchen Übertragungen und der Verarbeitung Ihrer Daten zu.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">Kontakt</h4>
                              <p>Wenn Sie Fragen oder Bedenken bezüglich unserer Datenschutzrichtlinie oder der Verarbeitung Ihrer personenbezogenen Daten haben, können Sie uns unter folgender Adresse kontaktieren:</p>
                              <p className="mt-2"><strong>E-Mail:</strong> <a href="mailto:info@umzug-anbieter-vergleich.de" className="text-blue-600 hover:text-blue-700 underline transition-colors duration-200">info@umzug-anbieter-vergleich.de</a></p>
                              <p className="mt-2">Wir sind stets bemüht, Ihre Datenschutzanliegen zu behandeln und ermutigen Sie, uns zu kontaktieren, wenn Sie Fragen oder Beschwerden zu unserer Datenschutzrichtlinie haben.</p>
                              <p className="mt-2 text-gray-500">Zuletzt aktualisiert: 5. Februar 2025</p>
                            </div>
                          </>
                        ) : (
                          <>
                            <h3 className="text-lg font-bold mb-4">Privacy and Security Policy</h3>
                            <p>Protecting your privacy is important to us, and we are committed to protecting your personal data according to strict standards.</p>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">1. Safety</h4>
                              <p>The security of your personal data is our highest priority. We use Secure Sockets Layer (SSL) technology to protect your data. If your browser supports SSL, the information you enter on secure pages will be automatically encrypted before being sent over the internet.</p>
                              <p className="mt-2">A closed padlock or an unbroken key symbol in your browser indicates that you are connected to our secure server and your data is protected.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">2. Cookies</h4>
                              <p>We use cookies, small text files that are stored on your computer by your browser, to analyze how customers interact with our website.</p>
                              <p className="mt-2">These cookies help us improve our website and tailor it to your preferences. The data collected is used exclusively to optimize your user experience and is not shared with third parties.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">3. Registration</h4>
                              <p>We recommend that you register and log in to our website to use personalized features such as order status and individual information about your account.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">4. Place orders</h4>
                              <p>When you place an order, we collect the necessary information, including:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li>Your name</li>
                                <li>Your billing and shipping address</li>
                                <li>Your payment information</li>
                                <li>Your contact details</li>
                              </ul>
                              <p className="mt-2">This data helps us to process your order smoothly and provide you with a pleasant shopping experience. Your data will be used exclusively for processing your transaction.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">5. Sharing of information</h4>
                              <p>In order to provide you with our services, including verification, fraud prevention, payment processing and shipping, we may share your data with trusted business partners.</p>
                              <p className="mt-2">In certain cases, e.g. for fraud detection, personal data may be passed on to authorities or other organizations that store this information and can access it later.</p>
                              <p className="mt-2">We may also share data if required by law or necessary to protect our rights and property.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">6. Data storage</h4>
                              <p>We retain your personal data only for as long as necessary for the purposes for which it was collected. This includes legal, accounting, or reporting obligations.</p>
                              <p className="mt-2">Once your data is no longer needed, we will take appropriate measures to securely delete or anonymize it.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">7. Your data protection rights</h4>
                              <p>Depending on your location, you may have the following rights:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li>To request information about your personal data</li>
                                <li>To request the correction or deletion of your data</li>
                                <li>To object to the processing of your data in certain cases</li>
                              </ul>
                              <p className="mt-2">To exercise these rights, please contact us using the contact details provided below.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">8. Unsubscribing from marketing communications</h4>
                              <p>If you no longer wish to receive marketing emails from us, you can unsubscribe at any time:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li>Use the unsubscribe link at the bottom of our emails.</li>
                                <li>Contact us directly</li>
                              </ul>
                              <p className="mt-2">Please note that even after unsubscribing from promotional emails, you may still receive important transactional or administrative messages regarding your orders or account.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">9. Data protection for children</h4>
                              <p>Our website and services are not intended for children under 13 years of age.</p>
                              <p className="mt-2">We do not knowingly collect or store personal data from children under the age of 13. If we discover that a child under the age of 13 has provided us with personal data, we will delete it immediately.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">10. Changes to this Privacy Policy</h4>
                              <p>We reserve the right to update this privacy policy from time to time.</p>
                              <p className="mt-2">All changes will be published on this page, and the date of the last update will be adjusted at the top of the policy.</p>
                              <p className="mt-2">We recommend that you check this policy regularly to stay informed about how we protect your personal data.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">11. International Data Transfers</h4>
                              <p>If you are located outside the region where our website is operated, please note that your personal data may be transferred to and processed in another country.</p>
                              <p className="mt-2">By using our website and providing your information, you consent to such transfers and the processing of your data.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">Contact</h4>
                              <p>If you have any questions or concerns regarding our privacy policy or the processing of your personal data, you can contact us at the following address:</p>
                              <p className="mt-2"><strong>Email:</strong> <a href="mailto:info@umzug-anbieter-vergleich.de" className="text-blue-600 hover:text-blue-700 underline transition-colors duration-200">info@umzug-anbieter-vergleich.de</a></p>
                              <p className="mt-2">We are always committed to addressing your privacy concerns and encourage you to contact us if you have any questions or complaints about our privacy policy.</p>
                              <p className="mt-2 text-gray-500">Last updated: February 5, 2025</p>
                            </div>
                          </>
                        )}
                      </div>

                      <div className="sticky bottom-0 bg-gray-100 dark:bg-gray-800 p-4 border-t border-gray-200 dark:border-gray-700 flex justify-end">
                        <button
                          onClick={() => setIsPrivacyModalOpen(false)}
                          className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-colors duration-200"
                        >
                          {isGerman ? 'Schließen' : 'Close'}
                        </button>
                      </div>
                    </motion.div>
                  </motion.div>
                )}
              </div>
            </motion.div>

            {/* Mobile Benefits Section - Only visible on mobile */}
            <motion.div
              className="lg:hidden mt-4 p-3 sm:p-4 rounded-xl border backdrop-blur-sm"
              style={{
                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                borderColor: 'var(--theme-border)'
              }}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.8 }}
            >
              <div className="text-center">
                <h3 className="text-xl font-bold mb-4 bg-gradient-to-r from-green-400 via-blue-400 to-purple-400 bg-clip-text text-transparent">
                  {isGerman ? 'Partner-Vorteile' : 'Partner Benefits'}
                </h3>
                
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4">
                  {[
                    {
                      icon: '🎯',
                      title: isGerman ? 'Qualifizierte Leads' : 'Qualified Leads'
                    },
                    {
                      icon: '💰',
                      title: isGerman ? 'Mehr Umsatz' : 'More Revenue'
                    },
                    {
                      icon: '⚡',
                      title: isGerman ? 'Sofort-Updates' : 'Instant Updates'
                    }
                  ].map((benefit, index) => (
                    <div
                      key={index}
                      className="flex flex-col items-center p-2 rounded-lg border border-white/10 bg-white/5"
                    >
                      <div className="text-2xl mb-2">{benefit.icon}</div>
                      <div className="text-sm font-medium text-center" style={{ color: 'var(--theme-text)' }}>
                        {benefit.title}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="flex justify-center items-center space-x-4 text-sm">
                  <span className="font-bold text-green-400">27K+ {isGerman ? 'Umzüge' : 'Moves'}</span>
                  <span className="font-bold text-blue-400">86+ {isGerman ? 'Partner' : 'Partners'}</span>
                  <span className="font-bold text-purple-400">4.9★ {isGerman ? 'Bewertung' : 'Rating'}</span>
                </div>
              </div>
            </motion.div>
          </div>
        </div>

        {/* Right Side - Partner Benefits - Mobile Hidden, Desktop Visible */}
        <div className="hidden lg:block relative lg:w-0 lg:flex-1 lg:overflow-y-auto">
          <motion.div 
            className="h-full w-full flex items-center justify-center backdrop-blur-xl py-8"
            style={{ 
              background: 'linear-gradient(135deg, rgba(34, 197, 94, 0.1) 0%, rgba(59, 130, 246, 0.1) 50%, rgba(168, 85, 247, 0.1) 100%)',
              borderLeft: '1px solid rgba(255, 255, 255, 0.1)'
            }}
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 1, delay: 0.3 }}
          >
            {/* Background Pattern */}
            <div className="absolute inset-0 opacity-10">
              <svg width="100%" height="100%" className="absolute inset-0">
                <defs>
                  <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
                    <path d="M 40 0 L 0 0 0 40" fill="none" stroke="white" strokeWidth="1"/>
                  </pattern>
                </defs>
                <rect width="100%" height="100%" fill="url(#grid)" />
              </svg>
            </div>

            <div className="text-center p-4 sm:p-6 max-w-md relative z-10">
              <motion.div 
                className="text-5xl mb-6 relative"
                animate={{ 
                  scale: [1, 1.05, 1]
                }}
                transition={{ 
                  duration: 4, 
                  repeat: Infinity,
                  ease: "easeInOut"
                }}
              >
                🤝
              </motion.div>
              
              <motion.h3 
                className="text-3xl font-bold mb-4 bg-gradient-to-r from-green-400 via-blue-400 to-purple-400 bg-clip-text text-transparent"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.5 }}
              >
                {isGerman ? 'Partner-Vorteile' : 'Partner Benefits'}
              </motion.h3>
              
              <motion.p 
                className="text-lg mb-6 leading-relaxed" 
                style={{ color: 'var(--theme-muted)' }}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.6 }}
              >
                {isGerman 
                  ? 'Steigern Sie Ihren Umsatz mit qualifizierten Leads aus unserem Netzwerk.'
                  : 'Increase your revenue with qualified leads from our network.'
                }
              </motion.p>

              {/* Benefits */}
              <div className="space-y-3 mb-6">
                {[
                  {
                    icon: '🎯',
                    title: isGerman ? 'Qualifizierte Leads' : 'Qualified Leads',
                    desc: isGerman ? 'Nur echte Kundenanfragen' : 'Only genuine customer inquiries'
                  },
                  {
                    icon: '💰',
                    title: isGerman ? 'Mehr Umsatz' : 'More Revenue',
                    desc: isGerman ? 'Bis zu 30% mehr Aufträge' : 'Up to 30% more orders'
                  },
                  {
                    icon: '⚡',
                    title: isGerman ? 'Sofort-Updates' : 'Instant Updates',
                    desc: isGerman ? 'Neue Leads in Echtzeit' : 'New leads in real-time'
                  }
                ].map((benefit, index) => (
                  <motion.div
                    key={index}
                    className="flex items-center space-x-3 p-2 rounded-lg backdrop-blur-sm border border-white/10 bg-white/5"
                    initial={{ opacity: 0, x: -30 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.6, delay: 0.7 + index * 0.15 }}
                    whileHover={{ x: 5, scale: 1.02 }}
                  >
                    <div className="text-xl">
                      {benefit.icon}
                    </div>
                    <div className="text-left">
                      <div className="font-bold text-base" style={{ color: 'var(--theme-text)' }}>
                        {benefit.title}
                      </div>
                      <div className="text-xs" style={{ color: 'var(--theme-muted)' }}>
                        {benefit.desc}
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Stats */}
              <div className="grid grid-cols-3 gap-3">
                {[
                  { value: '27K+', label: isGerman ? 'Umzüge' : 'Moves', delay: 0.8 },
                  { value: '86+', label: isGerman ? 'Partner' : 'Partners', delay: 0.9 },
                  { value: '4.9★', label: isGerman ? 'Bewertung' : 'Rating', delay: 1.0 }
                ].map((stat, index) => (
                  <motion.div
                    key={stat.label}
                    className="p-2 rounded-lg backdrop-blur-sm bg-gradient-to-br from-white/10 to-white/5 border border-white/20"
                    initial={{ opacity: 0, y: 20, scale: 0.9 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    transition={{ 
                      delay: stat.delay, 
                      type: "spring", 
                      stiffness: 200 
                    }}
                    whileHover={{ 
                      scale: 1.05,
                      boxShadow: "0 10px 25px rgba(0, 0, 0, 0.1)"
                    }}
                  >
                    <div className="font-bold text-lg bg-gradient-to-r from-green-400 to-blue-400 bg-clip-text text-transparent">
                      {stat.value}
                    </div>
                    <div className="text-xs mt-1 font-medium" style={{ color: 'var(--theme-muted)' }}>
                      {stat.label}
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Trust Badge */}
              <motion.div
                className="mt-6 p-3 rounded-lg bg-gradient-to-r from-green-500/10 to-blue-500/10 border border-green-500/20"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 1.2 }}
              >
                <div className="flex items-center justify-center space-x-2">
                  <span className="text-sm">✅</span>
                  <span className="text-sm font-medium" style={{ color: 'var(--theme-text)' }}>
                    {isGerman ? 'Geprüfte Partner • SSL-gesichert' : 'Verified Partners • SSL Secured'}
                  </span>
                </div>
              </motion.div>
            </div>
          </motion.div>
        </div>
      </div>
    </>
  );
}