import React, { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { motion } from 'framer-motion';
import { useAuth } from '../src/contexts/AuthContext';
import { useLanguage } from '../src/contexts/LanguageContext';
import { useTheme } from '../src/contexts/ThemeContext';
import ThemeToggle from '../src/components/ui/ThemeToggle';
import LanguageToggle from '../src/components/ui/LanguageToggle';
import Button from '../src/components/ui/Button';
import Logo from '../src/components/ui/Logo';
import { API_BASE_URL } from '../src/lib/config';
import { translations } from '../src/lib/translations';

export default function PartnerRequest() {
  const router = useRouter();
  const { isAuthenticated, loading } = useAuth();
  const { t, isGerman } = useLanguage();
  const { mounted, isDark } = useTheme();
  
  const [formData, setFormData] = useState({
    companyName: '',
    contactPerson: '',
    email: '',
    phone: '',
    regions: [],
    isNationwide: false,
    availableEmployees: '',
    periodOfAvailability: '',
    budgetScope: [],
    companyDescription: ''
  }); // Password will be auto-generated by server
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState({});
  const [serverError, setServerError] = useState('');
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const [serviceTypes, setServiceTypes] = useState([]);
  const [loadingServiceTypes, setLoadingServiceTypes] = useState(true);
  const [isServiceDropdownOpen, setIsServiceDropdownOpen] = useState(false);
  const [isPrivacyModalOpen, setIsPrivacyModalOpen] = useState(false);
  const serviceDropdownRef = useRef(null);
  const previousErrorsRef = useRef({});

  useEffect(() => {
    if (isAuthenticated() && !loading) {
      router.push('/dashboard');
    }
  }, [isAuthenticated, loading, router]);

  // Service types are fixed to security only
  useEffect(() => {
    setServiceTypes([
      { id: 'security', name: isGerman ? 'Sicherheitsservice' : 'Security Service' }
    ]);
    setLoadingServiceTypes(false);
  }, [isGerman]);

  // Update error messages when language changes
  useEffect(() => {
    if (Object.keys(errors).length > 0) {
      // Re-validate to update error messages in current language
      const newErrors = {};

      // Company Name validation
      if (!formData.companyName.trim()) {
        newErrors.companyName = isGerman ? 'Unternehmensname ist erforderlich' : 'Company name is required';
      }

      // Contact Person validation
      if (!formData.contactPerson.trim()) {
        newErrors.contactPerson = isGerman ? 'Kontaktperson ist erforderlich' : 'Contact person is required';
      }

      // Email validation
      if (!formData.email.trim()) {
        newErrors.email = isGerman ? 'E-Mail ist erforderlich' : 'Email is required';
      } else if (!/^[a-zA-Z0-9._+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$/.test(formData.email.trim())) {
        newErrors.email = isGerman ? 'E-Mail ist ungültig' : 'Email is invalid';
      }

      // Phone validation
      if (!formData.phone.trim()) {
        newErrors.phone = isGerman ? 'Telefonnummer ist erforderlich' : 'Phone number is required';
      }

      // Regions validation
      if (formData.regions.length === 0) {
        newErrors.regions = isGerman ? 'Bitte wählen Sie mindestens eine Region aus' : 'Please select at least one region';
      }

      // Available Employees validation
      if (!formData.availableEmployees) {
        newErrors.availableEmployees = isGerman ? 'Anzahl Mitarbeiter ist erforderlich' : 'Number of employees is required';
      }

      // Availability Period validation
      if (!formData.periodOfAvailability) {
        newErrors.periodOfAvailability = isGerman ? 'Verfügbarkeitszeitraum ist erforderlich' : 'Availability period is required';
      }

      // Budget Scope validation
      if (formData.budgetScope.length === 0) {
        newErrors.budgetScope = isGerman ? 'Bitte wählen Sie mindestens einen Service aus' : 'Please select at least one service';
      }

      // Description validation
      if (!formData.companyDescription.trim()) {
        newErrors.companyDescription = isGerman ? 'Beschreibung ist erforderlich' : 'Description is required';
      }

      // Update errors only if there were existing errors for those fields
      const updatedErrors = {};
      Object.keys(errors).forEach(key => {
        if (newErrors[key]) {
          updatedErrors[key] = newErrors[key];
        }
      });

      if (Object.keys(updatedErrors).length > 0) {
        setErrors(updatedErrors);
      }
    }
  }, [isGerman, formData.companyName, formData.contactPerson, formData.email, formData.phone, formData.regions, formData.availableEmployees, formData.periodOfAvailability, formData.budgetScope, formData.companyDescription, errors]);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (serviceDropdownRef.current && !serviceDropdownRef.current.contains(event.target)) {
        setIsServiceDropdownOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;

    setFormData(prev => {
      if (name === 'regions') {
        // Handle regions with Bundesweit logic
        let updatedArray = [...prev[name]];
        const nonNationwideRegions = ['bw', 'by', 'be', 'bb', 'hb', 'hh', 'he', 'mv', 'ni', 'nrw', 'rp', 'sl', 'sn', 'st', 'sh', 'th'];

        if (value === 'nationwide') {
          if (checked) {
            // Select all regions when nationwide is checked
            updatedArray = [...nonNationwideRegions];
          } else {
            // Clear all when nationwide is unchecked
            updatedArray = [];
          }
        } else {
          // Handle regular region selection
          if (checked) {
            if (!updatedArray.includes(value)) {
              updatedArray.push(value);
            }
          } else {
            updatedArray = updatedArray.filter(item => item !== value);
          }
        }

        // Set isNationwide boolean if all regions are selected
        const allNonNationwideSelected = nonNationwideRegions.every(r => updatedArray.includes(r));
        const isNationwideChecked = allNonNationwideSelected && updatedArray.length === nonNationwideRegions.length;

        return {
          ...prev,
          [name]: updatedArray,
          isNationwide: isNationwideChecked
        };
      } else if (name === 'budgetScope') {
        // Handle checkbox arrays
        let updatedArray = [...prev[name]];
        if (checked) {
          if (!updatedArray.includes(value)) {
            updatedArray.push(value);
          }
        } else {
          updatedArray = updatedArray.filter(item => item !== value);
        }
        return {
          ...prev,
          [name]: updatedArray
        };
      }
      return {
        ...prev,
        [name]: type === 'checkbox' ? checked : value
      };
    });

    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  // Translate server error messages using translations file
  const getTranslatedError = (errorMsg) => {
    const lang = isGerman ? 'de' : 'en';
    const trans = translations[lang];

    // Try to find the error message in translations
    return trans.auth[errorMsg] || errorMsg;
  };

  const validateForm = () => {
    const newErrors = {};

    // Company Name validation
    if (!formData.companyName.trim()) {
      newErrors.companyName = isGerman ? 'Unternehmensname ist erforderlich' : 'Company name is required';
    }

    // Contact Person validation
    if (!formData.contactPerson.trim()) {
      newErrors.contactPerson = isGerman ? 'Kontaktperson ist erforderlich' : 'Contact person is required';
    }

    // Email validation
    if (!formData.email.trim()) {
      newErrors.email = isGerman ? 'E-Mail ist erforderlich' : 'Email is required';
    } else if (!/^[a-zA-Z0-9._+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$/.test(formData.email.trim())) {
      newErrors.email = isGerman ? 'E-Mail ist ungültig' : 'Email is invalid';
    }

    // Phone validation
    if (!formData.phone.trim()) {
      newErrors.phone = isGerman ? 'Telefonnummer ist erforderlich' : 'Phone number is required';
    }

    // Regions validation
    if (formData.regions.length === 0) {
      newErrors.regions = isGerman ? 'Bitte wählen Sie mindestens eine Region aus' : 'Please select at least one region';
    }

    // Available Employees validation
    if (!formData.availableEmployees) {
      newErrors.availableEmployees = isGerman ? 'Anzahl Mitarbeiter ist erforderlich' : 'Number of employees is required';
    }

    // Availability Period validation
    if (!formData.periodOfAvailability) {
      newErrors.periodOfAvailability = isGerman ? 'Verfügbarkeitszeitraum ist erforderlich' : 'Availability period is required';
    }

    // Budget Scope validation
    if (formData.budgetScope.length === 0) {
      newErrors.budgetScope = isGerman ? 'Bitte wählen Sie mindestens einen Service aus' : 'Please select at least one service';
    }

    // Description validation
    if (!formData.companyDescription.trim()) {
      newErrors.companyDescription = isGerman ? 'Beschreibung ist erforderlich' : 'Description is required';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Get the first error for top display and auto-focus
  const getFirstError = () => {
    const errorKeys = [
      'companyName', 'contactPerson', 'email', 'phone', 'regions', 'availableEmployees', 'periodOfAvailability', 'budgetScope', 'companyDescription'
    ];

    for (const key of errorKeys) {
      if (errors[key]) {
        return { field: key, message: errors[key] };
      }
    }

    return null;
  };

  // Auto-focus on problematic field
  const focusOnErrorField = () => {
    const firstError = getFirstError();
    if (firstError) {
      setTimeout(() => {
        const element = document.getElementById(firstError.field);
        if (element) {
          element.focus();
          element.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
      }, 100);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!validateForm()) {
      focusOnErrorField();
      return;
    }

    setIsSubmitting(true);
    
    try {
      // Send partner registration request to backend
      // Use imported API_BASE_URL from config
      const response = await fetch(`${API_BASE_URL}/auth/register-partner`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          companyName: formData.companyName,
          contactPerson: formData.contactPerson,  // ← String
          email: formData.email,  // ← Root level
          phone: formData.phone,  // ← Root level
          serviceType: 'security',
          address: {
            street: '',
            city: '',
            postalCode: '',
            country: ''
          },
          securityFormData: {
            regions: formData.regions,
            isNationwide: formData.isNationwide,
            budgetScope: formData.budgetScope,
            availableEmployees: formData.availableEmployees,
            periodOfAvailability: formData.periodOfAvailability,
            companyDescription: formData.companyDescription
          },
          services: ['security'],
          partnerType: 'basic',
          language: isGerman ? 'de' : 'en'
        }),
      });

      const result = await response.json();

      if (response.ok && result.success) {
        setSubmitSuccess(true);
        console.log('Registration successful:', result);

        // Clear any existing errors
        setErrors({});
        setServerError('');

        // Do not auto-redirect - let user click the button
      } else {
        // Handle validation errors
        if (result.errors && Array.isArray(result.errors)) {
          const newErrors = {};
          result.errors.forEach(error => {
            const field = error.path || error.param;
            const translatedMsg = getTranslatedError(error.msg);
            // Map backend nested fields to frontend fields
            if (field === 'contactPerson') newErrors.contactPerson = translatedMsg;
            else if (field === 'email') newErrors.email = translatedMsg;
            else if (field === 'phone') newErrors.phone = translatedMsg;
            else if (field === 'companyName') newErrors.companyName = translatedMsg;
            else if (field === 'securityFormData.regions') newErrors.regions = translatedMsg;
            else if (field === 'securityFormData.budgetScope') newErrors.budgetScope = translatedMsg;
            else if (field === 'securityFormData.availableEmployees') newErrors.availableEmployees = translatedMsg;
            else if (field === 'securityFormData.periodOfAvailability') newErrors.periodOfAvailability = translatedMsg;
            else if (field === 'securityFormData.companyDescription') newErrors.companyDescription = translatedMsg;
            else if (field === 'services') newErrors.services = translatedMsg;
            else newErrors.email = translatedMsg; // Default to email field
          });
          setErrors(newErrors);
          setServerError('');
        } else {
          // Handle specific error messages - show as server error
          setErrors({});
          if (result.message?.includes('email already exists')) {
            setServerError(
              isGerman
                ? 'Ein Partner mit dieser E-Mail-Adresse existiert bereits.'
                : 'A partner with this email address already exists.'
            );
          } else if (result.message?.includes('Services already registered')) {
            setServerError(
              isGerman
                ? 'Services bereits registriert: Sicherheitsservice. Duplizierte Services können nicht registriert werden, es sei denn, sie wurden zuvor abgelehnt.'
                : result.message
            );
          } else if (result.message?.includes('company name already exists') || result.message?.includes('Company') && result.message?.includes('already offers')) {
            setServerError(
              isGerman
                ? 'Ein Partner mit diesem Firmennamen bietet bereits diesen Service an.'
                : 'A partner with this company name already offers this service.'
            );
          } else {
            setServerError(
              result.message || (isGerman
                ? 'Partner-Registrierung fehlgeschlagen'
                : 'Partner registration failed')
            );
          }
        }
      }
      
    } catch (error) {
      console.error('Registration error:', error);
      setErrors({ 
        email: isGerman 
          ? 'Netzwerkfehler. Bitte versuchen Sie es erneut.' 
          : 'Network error. Please try again.' 
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!mounted) {
    return null;
  }

  if (loading) {
    return (
      <div 
        className="min-h-screen flex items-center justify-center"
        style={{ 
          backgroundColor: 'var(--theme-bg)',
          backgroundImage: 'radial-gradient(circle at 25% 25%, rgba(99, 102, 241, 0.1) 0%, transparent 50%), radial-gradient(circle at 75% 75%, rgba(236, 72, 153, 0.1) 0%, transparent 50%)'
        }}
      >
        <motion.div
          className="flex flex-col items-center space-y-4"
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
        >
          <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
          <p style={{ color: 'var(--theme-text)' }}>
            {isGerman ? 'Wird geladen...' : 'Loading...'}
          </p>
        </motion.div>
      </div>
    );
  }

  if (isAuthenticated()) {
    return null;
  }

  if (submitSuccess) {
    return (
      <div 
        className="min-h-screen flex items-center justify-center relative overflow-hidden"
        style={{ 
          backgroundColor: 'var(--theme-bg)', 
          color: 'var(--theme-text)',
          backgroundImage: 'radial-gradient(circle at 25% 25%, rgba(99, 102, 241, 0.1) 0%, transparent 50%), radial-gradient(circle at 75% 75%, rgba(236, 72, 153, 0.1) 0%, transparent 50%)'
        }}
      >
        <motion.div
          className="text-center p-8 max-w-md mx-4"
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6 }}
        >
          <motion.div
            className="text-6xl mb-6"
            animate={{ rotate: [0, 10, -10, 0], scale: [1, 1.1, 1] }}
            transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
          >
            ✅
          </motion.div>
          <h2 className="text-3xl font-bold mb-4">
            {isGerman ? 'Anfrage gesendet!' : 'Request Sent!'}
          </h2>
          <p className="text-lg mb-4" style={{ color: 'var(--theme-muted)' }}>
            {isGerman
              ? 'Vielen Dank für Ihr Interesse! Wir werden uns bald bei Ihnen melden.'
              : 'Thank you for your interest! We will contact you soon.'
            }
          </p>

          <motion.div
            className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 rounded-lg p-4 mb-6"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
          >
            <div className="flex items-start space-x-3">
              <svg className="w-5 h-5 text-blue-600 dark:text-blue-400 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              <p className="text-sm text-blue-800 dark:text-blue-200">
                {isGerman
                  ? 'Eine Bestätigungs-E-Mail wurde an Ihre E-Mail-Adresse gesendet. Bitte überprüfen Sie Ihr Postfach.'
                  : 'A confirmation email has been sent to your email address. Please check your inbox.'
                }
              </p>
            </div>
          </motion.div>

          <motion.button
            onClick={() => router.push('/partner-login')}
            className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-semibold py-3 px-6 rounded-lg shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center space-x-2"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.6 }}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
          >
            <span>{isGerman ? 'Zur Anmeldung' : 'Go to Login'}</span>
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </motion.button>
        </motion.div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>
          {isGerman ? 'Registrieren - Business Connected' : 'Register - Business Connected'}
        </title>
        <meta name="description" content={isGerman ? 'Erstellen Sie Ihr kostenloses Business Connected Konto' : 'Create your free Business Connected account'} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes" />
        <style>{`
          input::placeholder,
          textarea::placeholder,
          select::placeholder {
            color: var(--theme-muted) !important;
            opacity: 0.7 !important;
          }

          select option {
            background-color: var(--theme-bg-secondary, rgba(0, 0, 0, 0.05)) !important;
            color: var(--theme-text) !important;
          }

          select option:hover {
            background-color: var(--theme-accent) !important;
            color: white !important;
          }

          select option:checked {
            background-color: var(--theme-accent) !important;
            color: white !important;
          }
        `}</style>
      </Head>

      <div
        className="min-h-screen flex flex-col relative"
        style={{
          backgroundColor: 'var(--theme-bg)',
          color: 'var(--theme-text)',
          backgroundImage: 'radial-gradient(circle at 25% 25%, rgba(99, 102, 241, 0.1) 0%, transparent 50%), radial-gradient(circle at 75% 75%, rgba(236, 72, 153, 0.1) 0%, transparent 50%)'
        }}
      >
        {/* Animated Background Elements */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <motion.div
            className="absolute top-20 left-20 w-32 h-32 bg-gradient-to-r from-blue-400 to-purple-500 rounded-full opacity-20 blur-3xl"
            animate={{
              x: [0, 50, 0],
              y: [0, -30, 0],
              scale: [1, 1.2, 1],
            }}
            transition={{
              duration: 8,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
          <motion.div
            className="absolute bottom-20 right-20 w-48 h-48 bg-gradient-to-r from-pink-400 to-red-500 rounded-full opacity-20 blur-3xl"
            animate={{
              x: [0, -40, 0],
              y: [0, 20, 0],
              scale: [1, 0.8, 1],
            }}
            transition={{
              duration: 10,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
          <motion.div
            className="absolute top-1/2 left-1/3 w-20 h-20 bg-gradient-to-r from-green-400 to-cyan-500 rounded-full opacity-30 blur-2xl"
            animate={{
              rotate: [0, 360],
              scale: [1, 1.5, 1],
            }}
            transition={{
              duration: 15,
              repeat: Infinity,
              ease: "linear"
            }}
          />
        </div>

        {/* Main Form Container */}
        <div className="flex-1 flex flex-col py-4 sm:py-6 px-4 sm:px-6 lg:px-8 lg:w-1/2 relative z-10 overflow-y-auto">
          <div className="mx-auto w-full max-w-sm sm:max-w-md lg:max-w-2xl my-auto">
            {/* Header Controls */}
            <motion.div
              className="flex items-center justify-between mb-6 sm:mb-8 lg:mb-12"
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <Logo />
              <div className="flex items-center space-x-2 sm:space-x-3">
                <LanguageToggle />
                <ThemeToggle />
              </div>
            </motion.div>

            {/* Partner Request Card */}
            <motion.div
              className="backdrop-blur-xl rounded-2xl p-6 sm:p-8 border shadow-2xl relative"
              style={{
                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                borderColor: 'var(--theme-border)',
                boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)'
              }}
              initial={{ opacity: 0, y: 30, scale: 0.9 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              transition={{ duration: 0.8, delay: 0.2 }}
            >
              {/* Glass Effect Overlay */}
              <div className="absolute inset-0 bg-gradient-to-br from-white/10 to-white/5 rounded-2xl pointer-events-none" />
              
              <div className="relative z-10">
                {/* Back Button */}
                <motion.div
                  className="mb-4"
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.5 }}
                >
                  <Link
                    href="/partner-login"
                    className="inline-flex items-center text-sm font-medium transition-all duration-200 hover:opacity-75"
                    style={{ color: 'var(--theme-accent)' }}
                  >
                    <motion.span
                      animate={{ x: [-2, 0, -2] }}
                      transition={{ duration: 1.5, repeat: Infinity, ease: "easeInOut" }}
                      className="mr-2"
                    >
                      ←
                    </motion.span>
                    {isGerman ? 'Zurück zur Anmeldung' : 'Back to Login'}
                  </Link>
                </motion.div>

                <div className="text-center mb-6 sm:mb-8 lg:mb-10">
                  <motion.div
                    className="w-16 h-16 sm:w-20 sm:h-20 mx-auto mb-4 sm:mb-6 bg-gradient-to-br from-blue-500 via-purple-500 to-pink-500 rounded-2xl flex items-center justify-center shadow-lg"
                    initial={{ scale: 0, rotate: -180 }}
                    animate={{ scale: 1, rotate: 0 }}
                    transition={{
                      type: "spring",
                      stiffness: 200,
                      damping: 15,
                      delay: 0.4
                    }}
                    whileHover={{
                      scale: 1.1,
                      rotate: 10,
                      boxShadow: "0 10px 25px rgba(99, 102, 241, 0.4)"
                    }}
                  >
                    <span className="text-2xl sm:text-3xl text-white">🤝</span>
                  </motion.div>
                  <motion.h2
                    className="text-2xl sm:text-3xl font-bold mb-2 sm:mb-3 bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.5 }}
                  >
                    {isGerman ? 'Registrieren' : 'Create Account'}
                  </motion.h2>
                  <motion.p
                    className="text-base sm:text-lg"
                    style={{ color: 'var(--theme-muted)' }}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.6 }}
                  >
                    {isGerman 
                      ? 'Erstellen Sie Ihr Business Connected Konto'
                      : 'Create your Business Connected Partner account'
                    }
                  </motion.p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-4 sm:space-y-6">
                  {/* Server Error Message */}
                  {serverError && (
                    <motion.div
                      initial={{ opacity: 0, scale: 0.9 }}
                      animate={{ opacity: 1, scale: 1 }}
                      className="p-4 rounded-xl border border-red-400/30 bg-red-50 text-red-700 text-sm text-center"
                      style={{
                        backgroundColor: 'rgba(239, 68, 68, 0.1)',
                        borderColor: 'rgba(239, 68, 68, 0.3)',
                        color: '#991b1b'
                      }}
                    >
                      ⚠️ {serverError}
                    </motion.div>
                  )}

                  {/* Company Name - Full Width */}
                  <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.7 }}
                  >
                    <label
                      htmlFor="companyName"
                      className="block text-sm font-semibold mb-3"
                      style={{ color: 'var(--theme-text)' }}
                    >
                      🏢 {isGerman ? 'Unternehmensname' : 'Company Name'}
                    </label>
                    <div className="relative">
                      <input
                        id="companyName"
                        name="companyName"
                        type="text"
                        required
                        value={formData.companyName}
                        onChange={handleChange}
                        className={`
                          appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 rounded-xl
                          backdrop-blur-sm transition-all duration-300
                          focus:outline-none focus:ring-4 focus:ring-opacity-30 focus:scale-105 text-sm sm:text-base
                          border-gray-300 dark:border-gray-300
                          ${errors.companyName ? 'focus:border-red-400 focus:ring-red-400' : 'focus:border-blue-400 focus:ring-blue-400'}
                        `}
                        style={{
                          backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05)) !important',
                          borderColor: errors.companyName ? '#EF4444' : 'var(--theme-border)',
                          color: 'var(--theme-text)',
                          backdropFilter: 'blur(10px)'
                        }}
                        placeholder={isGerman ? 'Unternehmensname eingeben' : 'Enter company name'}
                      />
                      {errors.companyName && <p className="text-red-500 text-sm mt-1">{errors.companyName}</p>}
                    </div>
                  </motion.div>

                  {/* Contact Person - Full Width */}
                  <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.75 }}
                  >
                    <label
                      htmlFor="contactPerson"
                      className="block text-sm font-semibold mb-3"
                      style={{ color: 'var(--theme-text)' }}
                    >
                      👤 {isGerman ? 'Kontaktperson' : 'Contact Person'}
                    </label>
                    <div className="relative">
                      <input
                        id="contactPerson"
                        name="contactPerson"
                        type="text"
                        required
                        value={formData.contactPerson}
                        onChange={handleChange}
                        className={`
                          appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 rounded-xl
                          backdrop-blur-sm transition-all duration-300
                          focus:outline-none focus:ring-4 focus:ring-opacity-30 focus:scale-105 text-sm sm:text-base
                          border-gray-300 dark:border-gray-300
                          ${errors.contactPerson ? 'focus:border-red-400 focus:ring-red-400' : 'focus:border-blue-400 focus:ring-blue-400'}
                        `}
                        style={{
                          backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05)) !important',
                          borderColor: errors.contactPerson ? '#EF4444' : 'var(--theme-border)',
                          color: 'var(--theme-text)',
                          backdropFilter: 'blur(10px)'
                        }}
                        placeholder={isGerman ? 'Name der Kontaktperson' : 'Enter contact person name'}
                      />
                      {errors.contactPerson && <p className="text-red-500 text-sm mt-1">{errors.contactPerson}</p>}
                    </div>
                  </motion.div>

                  {/* Email and Phone - Two Columns */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {/* Email */}
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.9 }}
                    >
                      <label 
                        htmlFor="email" 
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        📧 E-Mail
                      </label>
                      <div className="relative">
                        <input
                          id="email"
                          name="email"
                          type="email"
                          required
                          value={formData.email}
                          onChange={handleChange}
                          onInvalid={(e) => {
                            e.target.setCustomValidity(
                              isGerman
                                ? 'Bitte füllen Sie dieses Feld aus.'
                                : 'Please fill in this field.'
                            );
                          }}
                          onInput={(e) => e.target.setCustomValidity('')}
                          className={`
                            appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 rounded-xl
                            backdrop-blur-sm transition-all duration-300
                            focus:outline-none focus:ring-4 focus:ring-opacity-30 focus:scale-105 text-sm sm:text-base
                            border-gray-300 dark:border-gray-300
                            ${errors.email ? 'focus:border-red-400 focus:ring-red-400' : 'focus:border-blue-400 focus:ring-blue-400'}
                          `}
                          style={{
                            backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05)) !important',
                            borderColor: errors.email ? '#EF4444' : 'var(--theme-border)',
                            color: 'var(--theme-text)',
                            backdropFilter: 'blur(10px)'
                          }}
                          placeholder={isGerman ? 'E-Mail-Adresse eingeben' : 'Enter email address'}
                        />
                      </div>
                    </motion.div>

                    {/* Phone */}
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 1.0 }}
                    >
                      <label 
                        htmlFor="phone" 
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        📞 {isGerman ? 'Telefonnummer' : 'Phone Number'}
                      </label>
                      <div className="relative">
                        <input
                          id="phone"
                          name="phone"
                          type="tel"
                          required
                          value={formData.phone}
                          onChange={handleChange}
                          onInvalid={(e) => {
                            e.target.setCustomValidity(
                              isGerman
                                ? 'Bitte füllen Sie dieses Feld aus.'
                                : 'Please fill in this field.'
                            );
                          }}
                          onInput={(e) => e.target.setCustomValidity('')}
                          className={`
                            appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 rounded-xl
                            backdrop-blur-sm transition-all duration-300
                            focus:outline-none focus:ring-4 focus:ring-opacity-30 focus:scale-105 text-sm sm:text-base
                            border-gray-300 dark:border-gray-300
                            ${errors.phone ? 'focus:border-red-400 focus:ring-red-400' : 'focus:border-blue-400 focus:ring-blue-400'}
                          `}
                          style={{
                            backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05)) !important',
                            borderColor: errors.phone ? '#EF4444' : 'var(--theme-border)',
                            color: 'var(--theme-text)',
                            backdropFilter: 'blur(10px)'
                          }}
                          placeholder={isGerman ? 'Telefonnummer eingeben' : 'Enter phone number'}
                        />
                      </div>
                    </motion.div>
                  </div>

                  {/* Service is fixed to moving - no selection needed */}

                  {/* Regions - Full Width */}
                  <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.9 }}
                    className="mt-6 mb-6"
                  >
                    <label className="block text-sm font-semibold mb-3" style={{ color: 'var(--theme-text)' }}>
                      🗺️ In welchen Regionen sind Einsätze möglich?
                    </label>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
                      {[
                        { id: 'bw', label: 'Baden-Württemberg' },
                        { id: 'by', label: 'Bayern' },
                        { id: 'be', label: 'Berlin' },
                        { id: 'bb', label: 'Brandenburg' },
                        { id: 'hb', label: 'Bremen' },
                        { id: 'hh', label: 'Hamburg' },
                        { id: 'he', label: 'Hessen' },
                        { id: 'mv', label: 'Mecklenburg-Vorpommern' },
                        { id: 'ni', label: 'Niedersachsen' },
                        { id: 'nrw', label: 'Nordrhein-Westfalen' },
                        { id: 'rp', label: 'Rheinland-Pfalz' },
                        { id: 'sl', label: 'Saarland' },
                        { id: 'sn', label: 'Sachsen' },
                        { id: 'st', label: 'Sachsen-Anhalt' },
                        { id: 'sh', label: 'Schleswig-Holstein' },
                        { id: 'th', label: 'Thüringen' },
                        { id: 'nationwide', label: 'Bundesweit' }
                      ].map(region => (
                        <label key={region.id} className="flex items-center space-x-2 cursor-pointer">
                          <input
                            type="checkbox"
                            name="regions"
                            value={region.id}
                            checked={formData.regions.includes(region.id)}
                            onChange={handleChange}
                            className="w-4 h-4 rounded flex-shrink-0"
                          />
                          <span style={{ color: 'var(--theme-text)' }} className="text-xs sm:text-sm break-words">{region.label}</span>
                        </label>
                      ))}
                    </div>
                    {errors.regions && <p className="text-red-500 text-sm mt-2">{errors.regions}</p>}
                  </motion.div>

                  {/* Available Employees and Availability Period - Two Columns */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 1.0 }}
                    >
                      <label
                        htmlFor="availableEmployees"
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        👥 {isGerman ? 'Anzahl verfügbarer Mitarbeiter' : 'Number of available employees'}
                      </label>
                      <select
                        id="availableEmployees"
                        name="availableEmployees"
                        value={formData.availableEmployees}
                        onChange={handleChange}
                        className={`
                          relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 rounded-xl
                          backdrop-blur-sm transition-all duration-300
                          focus:outline-none focus:ring-4 focus:ring-opacity-30 focus:scale-105 text-sm sm:text-base
                          border-gray-300 dark:border-gray-300
                          ${errors.availableEmployees ? 'focus:border-red-400 focus:ring-red-400' : 'focus:border-blue-400 focus:ring-blue-400'}
                        `}
                        style={{
                          backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05)) !important',
                          borderColor: errors.availableEmployees ? '#EF4444' : 'var(--theme-border)',
                          color: 'var(--theme-text)',
                          backdropFilter: 'blur(10px)'
                        }}
                      >
                        <option value="">{isGerman ? 'Bitte wählen...' : 'Please select...'}</option>
                        <option value="1_5">{isGerman ? '1 - 5 Mitarbeiter' : '1 - 5 Employees'}</option>
                        <option value="6_10">{isGerman ? '6 - 10 Mitarbeiter' : '6 - 10 Employees'}</option>
                        <option value="11_25">{isGerman ? '11 - 25 Mitarbeiter' : '11 - 25 Employees'}</option>
                        <option value="26_50">{isGerman ? '26 - 50 Mitarbeiter' : '26 - 50 Employees'}</option>
                        <option value="51_plus">{isGerman ? '51+ Mitarbeiter' : '51+ Employees'}</option>
                      </select>
                      {errors.availableEmployees && <p className="text-red-500 text-sm mt-1">{errors.availableEmployees}</p>}
                    </motion.div>

                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 1.1 }}
                    >
                      <label
                        htmlFor="periodOfAvailability"
                        className="block text-sm font-semibold mb-3"
                        style={{ color: 'var(--theme-text)' }}
                      >
                        ⏰ Verfügbarkeitszeitraum
                      </label>
                      <select
                        id="periodOfAvailability"
                        name="periodOfAvailability"
                        value={formData.periodOfAvailability}
                        onChange={handleChange}
                        className={`
                          relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 rounded-xl
                          backdrop-blur-sm transition-all duration-300
                          focus:outline-none focus:ring-4 focus:ring-opacity-30 focus:scale-105 text-sm sm:text-base
                          border-gray-300 dark:border-gray-300
                          ${errors.periodOfAvailability ? 'focus:border-red-400 focus:ring-red-400' : 'focus:border-blue-400 focus:ring-blue-400'}
                        `}
                        style={{
                          backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05)) !important',
                          borderColor: errors.periodOfAvailability ? '#EF4444' : 'var(--theme-border)',
                          color: 'var(--theme-text)',
                          backdropFilter: 'blur(10px)'
                        }}
                      >
                        <option value="">Bitte wählen...</option>
                        <option value="next_1_month">1 Monat</option>
                        <option value="next_3_months">bis zu 3 Monate</option>
                        <option value="next_6_months">bis zu 6 Monate</option>
                        <option value="ongoing">Dauerhaft verfügbar</option>
                        <option value="seasonal">Saisonal</option>
                      </select>
                      {errors.periodOfAvailability && <p className="text-red-500 text-sm mt-1">{errors.periodOfAvailability}</p>}
                    </motion.div>
                  </div>

                  {/* Budget Scope - Full Width */}
                  <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 1.2 }}
                    className="mt-6 mb-6"
                  >
                    <label className="block text-sm font-semibold mb-3" style={{ color: 'var(--theme-text)' }}>
                      💰 Sicherheitsdienste - Welche Services bieten Sie an?
                    </label>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
                      {[
                        { id: 'sicherheitsdienst', label: 'Sicherheitsdienst' },
                        { id: 'objektschutz', label: 'Objektschutz' },
                        { id: 'werkschutz', label: 'Werkschutz' },
                        { id: 'baustellenbewachung', label: 'Baustellenbewachung' },
                        { id: 'revierdienst', label: 'Revierdienst' },
                        { id: 'citystreife', label: 'Citystreife' },
                        { id: 'pfoertner', label: 'Pförtner' },
                        { id: 'empfangsdienst', label: 'Empfangsdienst' },
                        { id: 'personenschutz', label: 'Personenschutz' },
                        { id: 'tuersteher', label: 'Türsteher' },
                        { id: 'diensthundfuehrer', label: 'Diensthundeführer' },
                        { id: 'detektiv', label: 'Detektiv' },
                        { id: 'veranstaltungsschutz', label: 'Veranstaltungsschutz' },
                        { id: 'fluechtlingsheimbewachung', label: 'Flüchtlingsheimbewachung' },
                        { id: 'brandwache', label: 'Brandwache' }
                      ].map(scope => (
                        <label key={scope.id} className="flex items-center space-x-2 cursor-pointer">
                          <input
                            type="checkbox"
                            name="budgetScope"
                            value={scope.id}
                            checked={formData.budgetScope.includes(scope.id)}
                            onChange={handleChange}
                            className="w-4 h-4 rounded flex-shrink-0"
                          />
                          <span style={{ color: 'var(--theme-text)' }} className="text-xs sm:text-sm break-words">{scope.label}</span>
                        </label>
                      ))}
                    </div>
                    {errors.budgetScope && <p className="text-red-500 text-sm mt-2">{errors.budgetScope}</p>}
                  </motion.div>

                  {/* Description - Full Width */}
                  <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 1.3 }}
                    className="mt-6 mb-6"
                  >
                    <label
                      htmlFor="companyDescription"
                      className="block text-sm font-semibold mb-3"
                      style={{ color: 'var(--theme-text)' }}
                    >
                      💬 Kommentare und Notizen
                    </label>
                    <textarea
                      id="companyDescription"
                      name="companyDescription"
                      value={formData.companyDescription}
                      onChange={handleChange}
                      rows="2"
                      className={`
                        appearance-none relative block w-full px-3 py-3 sm:px-4 sm:py-4 border-2 rounded-xl
                        backdrop-blur-sm transition-all duration-300
                        focus:outline-none focus:ring-4 focus:ring-opacity-30 focus:scale-105 text-sm sm:text-base
                        border-gray-300 dark:border-gray-300
                        ${errors.companyDescription ? 'focus:border-red-400 focus:ring-red-400' : 'focus:border-blue-400 focus:ring-blue-400'}
                      `}
                      style={{
                        backgroundColor: 'var(--theme-bg-secondary, rgba(0, 0, 0, 0.05)) !important',
                        borderColor: errors.companyDescription ? '#EF4444' : 'var(--theme-border)',
                        color: 'var(--theme-text)',
                        backdropFilter: 'blur(10px)'
                      }}
                      placeholder="Kommentare und Notizen eingeben..."
                    />
                    {errors.companyDescription && <p className="text-red-500 text-sm mt-1">{errors.companyDescription}</p>}
                  </motion.div>

                  {/* Submit Button */}
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 1.6 }}
                  >
                    <Button
                      type="submit"
                      disabled={isSubmitting}
                      loading={isSubmitting}
                      variant="primary"
                      size="lg"
                      fullWidth
                      className="group relative text-sm sm:text-base font-bold text-white focus:ring-4 focus:ring-blue-500/30 bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 hover:from-blue-700 hover:via-purple-700 hover:to-pink-700"
                    >
                      {!isSubmitting && (
                        <>
                          <motion.span
                            animate={{ rotate: [0, 10, -10, 0] }}
                            transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
                            className="mr-2 text-lg"
                          >
                            🚀
                          </motion.span>
                          <span>{isGerman ? 'Als Partner registrieren' : 'Register as Partner'}</span>
                          <motion.span
                            animate={{ x: [0, 5, 0] }}
                            transition={{ duration: 1.5, repeat: Infinity, ease: "easeInOut" }}
                            className="ml-2"
                          >
                            →
                          </motion.span>
                        </>
                      )}
                      {isSubmitting && (
                        <span>{isGerman ? 'Partner-Registrierung läuft...' : 'Registering partner...'}</span>
                      )}
                    </Button>
                  </motion.div>

                  {/* Back to Login Link */}
                  <motion.div 
                    className="text-center mt-6 pt-4 sm:mt-8 sm:pt-6 border-t border-gray-200/20"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 1.6 }}
                  >
                    <span className="text-sm" style={{ color: 'var(--theme-muted)' }}>
                      {isGerman ? 'Bereits registriert?' : 'Already registered?'}{' '}
                      <Link
                        href="/partner-login"
                        className="font-semibold transition-all duration-200 hover:underline bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent"
                      >
                        {isGerman ? 'Anmelden' : 'Sign In'}
                      </Link>
                    </span>
                  </motion.div>
                </form>

                {/* Privacy Policy Modal */}
                {isPrivacyModalOpen && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
                    onClick={() => setIsPrivacyModalOpen(false)}
                  >
                    <motion.div
                      initial={{ opacity: 0, scale: 0.95, y: 20 }}
                      animate={{ opacity: 1, scale: 1, y: 0 }}
                      exit={{ opacity: 0, scale: 0.95, y: 20 }}
                      onClick={(e) => e.stopPropagation()}
                      className="bg-white dark:bg-gray-900 rounded-2xl shadow-2xl max-w-2xl w-full max-h-[80vh] overflow-y-auto"
                    >
                      <div className="sticky top-0 bg-gradient-to-r from-blue-600 to-purple-600 p-6 flex justify-between items-center z-10">
                        <h2 className="text-2xl font-bold text-white">
                          {isGerman ? 'Datenschutz' : 'Data Protection'}
                        </h2>
                        <button
                          onClick={() => setIsPrivacyModalOpen(false)}
                          className="text-white hover:bg-white/20 rounded-lg p-2 transition-colors duration-200"
                        >
                          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      </div>

                      <div className="p-6 space-y-4 text-sm leading-relaxed" style={{ color: 'var(--theme-text)' }}>
                        {isGerman ? (
                          <>
                            <h3 className="text-lg font-bold mb-4">Datenschutz- und Sicherheitsrichtlinie</h3>
                            <p>Der Schutz Ihrer Privatsphäre ist uns wichtig, und wir verpflichten uns, Ihre personenbezogenen Daten gemäß strengen Standards zu schützen.</p>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">1. Formulare und Kommentare</h4>
                              <p>Wenn Besucher Kommentare oder Formulare auf der Website ausfüllen, sammeln wir die Daten, die im Formular angezeigt werden, außerdem die IP-Adresse des Besuchers und den User-Agent-String (damit wird der Browser identifiziert), um die Erkennung von Spam zu unterstützen.</p>
                              <p className="mt-2">Aus deiner E-Mail-Adresse kann eine anonymisierte Zeichenfolge erstellt (auch Hash genannt) und dem Gravatar-Dienst übergeben werden, um zu prüfen, ob du diesen benutzt. Die Datenschutzerklärung des Gravatar-Dienstes findest du hier: https://automattic.com/privacy/. Nachdem dein Kommentar freigegeben wurde, ist dein Profilbild öffentlich im Kontext deines Kommentars sichtbar.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">2. Medien</h4>
                              <p>Wenn du ein registrierter Benutzer bist und Fotos auf diese Website lädst, solltest du vermeiden, Fotos mit einem EXIF-GPS-Standort hochzuladen. Besucher dieser Website könnten Fotos, die auf dieser Website gespeichert sind, herunterladen und deren Standort-Informationen extrahieren.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">3. Cookies</h4>
                              <p>Wenn du einen Kommentar auf unserer Website schreibst, kann das eine Einwilligung sein, deinen Namen, E-Mail-Adresse und Website in Cookies zu speichern. Dies ist eine Komfortfunktion, damit du nicht, wenn du einen weiteren Kommentar schreibst, all diese Daten erneut eingeben musst. Diese Cookies werden ein Jahr lang gespeichert.</p>
                              <p className="mt-2">Falls du ein Konto hast und dich auf dieser Website anmeldest, werden wir ein temporäres Cookie setzen, um festzustellen, ob dein Browser Cookies akzeptiert. Dieses Cookie enthält keine personenbezogenen Daten und wird verworfen, wenn du deinen Browser schließt.</p>
                              <p className="mt-2">Wenn du dich anmeldest, werden wir einige Cookies einrichten, um deine Anmeldeinformationen und Anzeigeoptionen zu speichern. Anmelde-Cookies verfallen nach zwei Tagen und Cookies für die Anzeigeoptionen nach einem Jahr. Falls du bei der Anmeldung &ldquo;Angemeldet bleiben&rdquo; auswählst, wird deine Anmeldung zwei Wochen lang aufrechterhalten. Mit der Abmeldung aus deinem Konto werden die Anmelde-Cookies gelöscht.</p>
                              <p className="mt-2">Wenn du einen Artikel bearbeitest oder veröffentlichst, wird ein zusätzlicher Cookie in deinem Browser gespeichert. Dieser Cookie enthält keine personenbezogenen Daten und verweist nur auf die Beitrags-ID des Artikels, den du gerade bearbeitet hast. Der Cookie verfällt nach einem Tag.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">4. Eingebettete Inhalte von anderen Websites</h4>
                              <p>Beiträge auf dieser Website können eingebettete Inhalte beinhalten (z. B. Videos, Bilder, Beiträge etc.). Eingebettete Inhalte von anderen Websites verhalten sich exakt so, als ob der Besucher die andere Website besucht hätte.</p>
                              <p className="mt-2">Diese Websites können Daten über dich sammeln, Cookies benutzen, zusätzliche Tracking-Dienste von Dritten einbetten und deine Interaktion mit diesem eingebetteten Inhalt aufzeichnen, inklusive deiner Interaktion mit dem eingebetteten Inhalt, falls du ein Konto hast und auf dieser Website angemeldet bist.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">5. Mit wem wir deine Daten teilen</h4>
                              <p>Wenn du eine Zurücksetzung des Passworts beantragst, wird deine IP-Adresse in der E-Mail zur Zurücksetzung enthalten sein.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">6. Wie lange wir deine Daten speichern</h4>
                              <p>Wenn du einen Kommentar schreibst, wird dieser inklusive Metadaten zeitlich unbegrenzt gespeichert. Auf diese Art können wir Folgekommentare automatisch erkennen und freigeben, anstatt sie in einer Moderations-Warteschlange festzuhalten.</p>
                              <p className="mt-2">Für Benutzer, die sich auf unserer Website registrieren, speichern wir zusätzlich die persönlichen Informationen, die sie in ihren Benutzerprofilen angeben. Alle Benutzer können jederzeit ihre persönlichen Informationen einsehen, verändern oder löschen (der Benutzername kann nicht verändert werden). Administratoren der Website können diese Informationen ebenfalls einsehen und verändern.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">7. Welche Rechte du an deinen Daten hast</h4>
                              <p>Wenn du ein Konto auf dieser Website besitzt oder Kommentare geschrieben hast, kannst du einen Export deiner personenbezogenen Daten bei uns anfordern, inklusive aller Daten, die du uns mitgeteilt hast. Darüber hinaus kannst du die Löschung aller personenbezogenen Daten, die wir von dir gespeichert haben, anfordern. Dies umfasst nicht die Daten, die wir aufgrund administrativer, rechtlicher oder sicherheitsrelevanter Notwendigkeiten aufbewahren müssen.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">8. Wohin deine Daten gesendet werden</h4>
                              <p>Besucher-Kommentare könnten von einem automatisierten Dienst zur Spam-Erkennung untersucht werden.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">9. Sicherheit</h4>
                              <p>Die Sicherheit Ihrer personenbezogenen Daten hat für uns höchste Priorität. Wir verwenden Secure Sockets Layer (SSL)-Technologie, um Ihre Daten zu schützen. Wenn Ihr Browser SSL unterstützt, werden die Informationen, die Sie auf sicheren Seiten eingeben, automatisch verschlüsselt, bevor sie über das Internet gesendet werden.</p>
                              <p className="mt-2">Ein geschlossenes Vorhängeschloss oder ein ungebrochenes Schlüsselsymbol in Ihrem Browser zeigt an, dass Sie mit unserem sicheren Server verbunden sind und Ihre Daten geschützt sind.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">10. Änderungen dieser Datenschutzrichtlinie</h4>
                              <p>Wir behalten uns das Recht vor, diese Datenschutzrichtlinie von Zeit zu Zeit zu aktualisieren.</p>
                              <p className="mt-2">Alle Änderungen werden auf dieser Seite veröffentlicht, und das Datum der letzten Aktualisierung wird oben in der Richtlinie angepasst.</p>
                              <p className="mt-2">Wir empfehlen Ihnen, diese Richtlinie regelmäßig zu überprüfen, um informiert zu bleiben, wie wir Ihre personenbezogenen Daten schützen.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">Kontakt</h4>
                              <p>Wenn Sie Fragen oder Bedenken bezüglich unserer Datenschutzrichtlinie oder der Verarbeitung Ihrer personenbezogenen Daten haben, können Sie uns unter folgender Adresse kontaktieren:</p>
                              <p className="mt-2"><strong>E-Mail:</strong> <a href="mailto:info@businessconnected24.de" className="text-blue-600 hover:text-blue-700 underline transition-colors duration-200">info@businessconnected24.de</a></p>
                              <p className="mt-2">Wir sind stets bemüht, Ihre Datenschutzanliegen zu behandeln und ermutigen Sie, uns zu kontaktieren, wenn Sie Fragen oder Beschwerden zu unserer Datenschutzrichtlinie haben.</p>
                              <p className="mt-2 text-gray-500">Zuletzt aktualisiert: 8. Januar 2026</p>
                            </div>
                          </>
                        ) : (
                          <>
                            <h3 className="text-lg font-bold mb-4">Privacy Policy</h3>
                            <p>When you provide information to us through this website, we are committed to protecting your privacy and ensuring transparency about how we handle your personal data. This privacy policy explains what information we collect, how we use it, and your rights regarding your data.</p>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">1. Forms and Comments</h4>
                              <p>When you submit the security services forms or contact information through our website, we collect the personal data you provide, including your name, email address, phone number, company information, and project details. We use this information exclusively to process your request and connect you with appropriate partners or provide requested information.</p>
                              <p className="mt-2">If you choose to enable it, your profile picture (avatar) may be displayed using Gravatar, which is a third-party service. Gravatar creates a hashed value of your email address to retrieve your avatar, but your email address is not directly shared with Gravatar in unhashed form.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">2. Media</h4>
                              <p>If you upload media files (images, documents, etc.) to our platform, please be aware that these files may contain sensitive metadata, including GPS coordinates (EXIF data). We recommend removing or stripping this data before uploading, as it may reveal location information or other personal details.</p>
                              <p className="mt-2">We take reasonable steps to prevent unauthorized access to uploaded files, but we recommend not uploading sensitive personal information.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">3. Cookies</h4>
                              <p>We use cookies and similar tracking technologies to enhance your experience on our website. The types of cookies we use include:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li><strong>Session Cookies:</strong> Retained for 1 year to maintain your login session and preferences</li>
                                <li><strong>Preference Cookies:</strong> Retained for 2 days to remember your language and display preferences</li>
                                <li><strong>Analytics Cookies:</strong> Retained for 2 weeks to help us understand how you use our website and improve functionality</li>
                              </ul>
                              <p className="mt-2">You can control cookie preferences through your browser settings. Disabling cookies may affect your ability to use certain features of our website.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">4. Embedded Content</h4>
                              <p>Our website may contain embedded content from third-party services (such as maps, videos, or analytics services). These third-party services may collect information about your interaction with the embedded content, including your IP address and user agent information.</p>
                              <p className="mt-2">We are not responsible for the privacy practices of these third-party services. We recommend reviewing their privacy policies for more information about how they handle your data.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">5. Sharing Your Data</h4>
                              <p>Your personal data will not be shared with third parties without your explicit consent, except in the following circumstances:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li><strong>Service Partners:</strong> We may share your email address with relevant security service providers when you submit a client request form, so they can contact you about your inquiry</li>
                                <li><strong>Password Reset:</strong> When you request a password reset, your IP address is temporarily used for security verification purposes</li>
                                <li><strong>Legal Requirements:</strong> We may disclose your information if required by law, regulation, or legal process</li>
                              </ul>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">6. Data Storage Duration</h4>
                              <p>We retain your personal data for the following periods:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li><strong>Form Submissions:</strong> Retained indefinitely unless you request deletion, for the purpose of ongoing communication and service provision</li>
                                <li><strong>User Profile Data:</strong> Retained indefinitely while your account is active, or for 90 days after account deletion unless required to retain for legal purposes</li>
                                <li><strong>Login Logs:</strong> Retained for 30 days for security purposes</li>
                                <li><strong>Analytics Data:</strong> Retained for 24 months to help us understand long-term trends</li>
                              </ul>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">7. Your Data Protection Rights</h4>
                              <p>Under applicable data protection laws (including the EU General Data Protection Regulation), you have the following rights regarding your personal data:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li><strong>Right of Access:</strong> You can request a copy of the personal data we hold about you</li>
                                <li><strong>Right to Rectification:</strong> You can request correction of inaccurate or incomplete data</li>
                                <li><strong>Right to Erasure:</strong> You can request deletion of your personal data (subject to certain legal exceptions)</li>
                                <li><strong>Right to Restrict Processing:</strong> You can request that we limit how we use your data</li>
                                <li><strong>Right to Data Portability:</strong> You can request your data in a portable format</li>
                                <li><strong>Right to Object:</strong> You can object to certain types of data processing</li>
                              </ul>
                              <p className="mt-2">To exercise any of these rights, please contact us using the contact details provided below.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">8. Data Transfer and Automated Processing</h4>
                              <p>To prevent spam and abuse, we use automated systems to analyze form submissions and user behavior. This may include:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li>Pattern detection to identify potentially fraudulent or spam submissions</li>
                                <li>Behavioral analysis to detect unusual account activity</li>
                                <li>Automated email verification</li>
                              </ul>
                              <p className="mt-2">If your submission is flagged as potentially spam or suspicious, it may be reviewed by our team before processing.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">9. Security</h4>
                              <p>We employ industry-standard security measures to protect your personal data:</p>
                              <ul className="list-disc list-inside mt-2 space-y-1">
                                <li><strong>SSL/TLS Encryption:</strong> All data transmitted between your browser and our servers is encrypted using Secure Sockets Layer (SSL) or Transport Layer Security (TLS) technology</li>
                                <li><strong>Secure Passwords:</strong> Passwords are hashed and salted before storage</li>
                                <li><strong>Access Controls:</strong> Access to personal data is restricted to authorized personnel only</li>
                                <li><strong>Regular Security Audits:</strong> We periodically review our security measures</li>
                              </ul>
                              <p className="mt-2">While we implement comprehensive security measures, no method of transmission over the internet is 100% secure. You use our services at your own risk, and we cannot guarantee absolute security.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">10. Changes to This Privacy Policy</h4>
                              <p>We reserve the right to update this privacy policy at any time to reflect changes in our data handling practices, legal requirements, or other factors. We will notify you of material changes by updating the date at the bottom of this policy and, in some cases, by sending you an email notification.</p>
                              <p className="mt-2">Your continued use of our website following any changes to this policy constitutes your acceptance of those changes. We recommend reviewing this policy regularly to stay informed about how we protect your data.</p>
                            </div>

                            <div>
                              <h4 className="font-bold mt-4 mb-2">Contact Us</h4>
                              <p>If you have any questions, concerns, or requests regarding this privacy policy or our handling of your personal data, please contact us at:</p>
                              <p className="mt-2"><strong>Email:</strong> <a href="mailto:info@businessconnected24.de" className="text-blue-600 hover:text-blue-700 underline transition-colors duration-200">info@businessconnected24.de</a></p>
                              <p className="mt-2">We are committed to responding to all data protection inquiries within 30 days and to working with you to resolve any concerns regarding the processing of your personal data.</p>
                              <p className="mt-2 text-gray-500">Last updated: January 8, 2026</p>
                            </div>
                          </>
                        )}
                      </div>

                      <div className="sticky bottom-0 bg-gray-100 dark:bg-gray-800 p-4 border-t border-gray-200 dark:border-gray-700 flex justify-end">
                        <button
                          onClick={() => setIsPrivacyModalOpen(false)}
                          className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-colors duration-200"
                        >
                          {isGerman ? 'Schließen' : 'Close'}
                        </button>
                      </div>
                    </motion.div>
                  </motion.div>
                )}
              </div>
            </motion.div>

            {/* Mobile Benefits Section - Only visible on mobile */}
            <motion.div
              className="lg:hidden mt-4 p-3 sm:p-4 rounded-xl border backdrop-blur-sm"
              style={{
                backgroundColor: 'rgba(255, 255, 255, 0.05)',
                borderColor: 'var(--theme-border)'
              }}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.8 }}
            >
              <div className="text-center">
                <h3 className="text-xl font-bold mb-4 bg-gradient-to-r from-green-400 via-blue-400 to-purple-400 bg-clip-text text-transparent">
                  {isGerman ? 'Partner-Vorteile' : 'Partner Benefits'}
                </h3>
                
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4">
                  {[
                    {
                      icon: '🎯',
                      title: isGerman ? 'Qualifizierte Leads' : 'Qualified Leads'
                    },
                    {
                      icon: '💰',
                      title: isGerman ? 'Mehr Umsatz' : 'More Revenue'
                    },
                    {
                      icon: '⚡',
                      title: isGerman ? 'Sofort-Updates' : 'Instant Updates'
                    }
                  ].map((benefit, index) => (
                    <div
                      key={index}
                      className="flex flex-col items-center p-2 rounded-lg border border-white/10 bg-white/5"
                    >
                      <div className="text-2xl mb-2">{benefit.icon}</div>
                      <div className="text-sm font-medium text-center" style={{ color: 'var(--theme-text)' }}>
                        {benefit.title}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="flex justify-center items-center space-x-4 text-sm">
                  <span className="font-bold text-green-400">27K+ {isGerman ? 'Umzüge' : 'Moves'}</span>
                  <span className="font-bold text-blue-400">86+ {isGerman ? 'Partner' : 'Partners'}</span>
                  <span className="font-bold text-purple-400">4.9★ {isGerman ? 'Bewertung' : 'Rating'}</span>
                </div>
              </div>
            </motion.div>
          </div>
        </div>

        {/* Right Side - Partner Benefits - Mobile Hidden, Desktop Visible */}
        <div className="hidden lg:block fixed lg:right-0 lg:top-0 lg:w-1/2 lg:h-screen lg:overflow-hidden">
          <motion.div
            className="h-screen w-full flex items-center justify-center backdrop-blur-xl py-8"
            style={{ 
              background: 'linear-gradient(135deg, rgba(34, 197, 94, 0.1) 0%, rgba(59, 130, 246, 0.1) 50%, rgba(168, 85, 247, 0.1) 100%)',
              borderLeft: '1px solid rgba(255, 255, 255, 0.1)'
            }}
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 1, delay: 0.3 }}
          >
            {/* Background Pattern */}
            <div className="absolute inset-0 opacity-10">
              <svg width="100%" height="100%" className="absolute inset-0">
                <defs>
                  <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
                    <path d="M 40 0 L 0 0 0 40" fill="none" stroke="white" strokeWidth="1"/>
                  </pattern>
                </defs>
                <rect width="100%" height="100%" fill="url(#grid)" />
              </svg>
            </div>

            {/* Floating Icons */}
            <div className="absolute inset-0 overflow-hidden pointer-events-none">
              <motion.div
                className="absolute top-10 left-10 text-4xl opacity-30"
                animate={{ y: [0, -20, 0], rotate: [0, 10, 0] }}
                transition={{ duration: 6, repeat: Infinity, ease: "easeInOut" }}
              >
                📊
              </motion.div>
              <motion.div
                className="absolute top-20 right-16 text-3xl opacity-40"
                animate={{ y: [0, 15, 0], rotate: [0, -15, 0] }}
                transition={{ duration: 4, repeat: Infinity, ease: "easeInOut", delay: 1 }}
              >
                🎯
              </motion.div>
              <motion.div
                className="absolute bottom-20 left-8 text-2xl opacity-25"
                animate={{ y: [0, -10, 0], x: [0, 10, 0] }}
                transition={{ duration: 5, repeat: Infinity, ease: "easeInOut", delay: 2 }}
              >
                💰
              </motion.div>
            </div>

            <div className="text-center p-4 sm:p-6 max-w-md relative z-10">
              <motion.div
                className="text-6xl sm:text-8xl mb-6 sm:mb-8 relative"
                animate={{
                  rotate: [0, 5, -5, 0],
                  scale: [1, 1.05, 1]
                }}
                transition={{
                  duration: 6,
                  repeat: Infinity,
                  ease: "easeInOut"
                }}
              >
                <div className="relative">
                  🤝
                  <motion.div
                    className="absolute -top-2 -right-2 w-6 h-6 bg-gradient-to-r from-green-400 to-blue-500 rounded-full"
                    animate={{
                      scale: [1, 1.3, 1],
                      opacity: [0.7, 1, 0.7]
                    }}
                    transition={{
                      duration: 2,
                      repeat: Infinity,
                      ease: "easeInOut"
                    }}
                  />
                </div>
              </motion.div>
              
              <motion.h3 
                className="text-3xl font-bold mb-4 bg-gradient-to-r from-green-400 via-blue-400 to-purple-400 bg-clip-text text-transparent"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.5 }}
              >
                {isGerman ? 'Partner-Vorteile' : 'Partner Benefits'}
              </motion.h3>
              
              <motion.p 
                className="text-lg mb-6 leading-relaxed" 
                style={{ color: 'var(--theme-muted)' }}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.6 }}
              >
                {isGerman 
                  ? 'Steigern Sie Ihren Umsatz mit qualifizierten Leads aus unserem Netzwerk.'
                  : 'Increase your revenue with qualified leads from our network.'
                }
              </motion.p>

              {/* Benefits */}
              <div className="space-y-3 mb-6">
                {[
                  {
                    icon: '🎯',
                    title: isGerman ? 'Qualifizierte Leads' : 'Qualified Leads',
                    desc: isGerman ? 'Nur echte Kundenanfragen' : 'Only genuine customer inquiries'
                  },
                  {
                    icon: '💰',
                    title: isGerman ? 'Mehr Umsatz' : 'More Revenue',
                    desc: isGerman ? 'Bis zu 30% mehr Aufträge' : 'Up to 30% more orders'
                  },
                  {
                    icon: '⚡',
                    title: isGerman ? 'Sofort-Updates' : 'Instant Updates',
                    desc: isGerman ? 'Neue Leads in Echtzeit' : 'New leads in real-time'
                  }
                ].map((benefit, index) => (
                  <motion.div
                    key={index}
                    className="flex items-center space-x-3 p-2 rounded-lg backdrop-blur-sm border border-white/10 bg-white/5"
                    initial={{ opacity: 0, x: -30 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.6, delay: 0.7 + index * 0.15 }}
                    whileHover={{ x: 5, scale: 1.02 }}
                  >
                    <div className="text-xl">
                      {benefit.icon}
                    </div>
                    <div className="text-left">
                      <div className="font-bold text-base" style={{ color: 'var(--theme-text)' }}>
                        {benefit.title}
                      </div>
                      <div className="text-xs" style={{ color: 'var(--theme-muted)' }}>
                        {benefit.desc}
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Stats */}
              <div className="grid grid-cols-3 gap-3">
                {[
                  { value: '27K+', label: isGerman ? 'Umzüge' : 'Moves', delay: 0.8 },
                  { value: '86+', label: isGerman ? 'Partner' : 'Partners', delay: 0.9 },
                  { value: '4.9★', label: isGerman ? 'Bewertung' : 'Rating', delay: 1.0 }
                ].map((stat, index) => (
                  <motion.div
                    key={stat.label}
                    className="p-2 rounded-lg backdrop-blur-sm bg-gradient-to-br from-white/10 to-white/5 border border-white/20"
                    initial={{ opacity: 0, y: 20, scale: 0.9 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    transition={{ 
                      delay: stat.delay, 
                      type: "spring", 
                      stiffness: 200 
                    }}
                    whileHover={{ 
                      scale: 1.05,
                      boxShadow: "0 10px 25px rgba(0, 0, 0, 0.1)"
                    }}
                  >
                    <div className="font-bold text-lg bg-gradient-to-r from-green-400 to-blue-400 bg-clip-text text-transparent">
                      {stat.value}
                    </div>
                    <div className="text-xs mt-1 font-medium" style={{ color: 'var(--theme-muted)' }}>
                      {stat.label}
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Trust Badge */}
              <motion.div
                className="mt-6 sm:mt-8 p-3 sm:p-4 rounded-xl bg-gradient-to-r from-green-500/10 to-blue-500/10 border border-green-500/20"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 1.2 }}
              >
                <div className="flex items-center justify-center space-x-2">
                  <motion.span
                    animate={{ rotate: [0, 360] }}
                    transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
                    className="text-lg"
                  >
                    🔒
                  </motion.span>
                  <span className="text-sm font-medium" style={{ color: 'var(--theme-text)' }}>
                    {isGerman ? 'Sicher & Geprüft' : 'Secure & Verified'}
                  </span>
                </div>
              </motion.div>
            </div>
          </motion.div>
        </div>
      </div>
    </>
  );
}

// Force server-side rendering to avoid NextRouter errors during static generation
export async function getServerSideProps() {
  return {
    props: {}
  };
}